# Headscale PVC
# 数据持久化存储
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: headscale
  namespace: beagle-access
  labels:
    app: headscale
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # 根据集群配置选择 StorageClass
  # storageClassName: local-path
