apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awecloud-signaling-server
  namespace: awecloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
