// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: pkg/proto/agent.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SystemInfo 系统信息
type SystemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`                                // 操作系统：linux / windows / darwin
	OsVersion     string                 `protobuf:"bytes,2,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"` // 系统版本
	Arch          string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`                            // CPU 架构：amd64 / arm64
	Hostname      string                 `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`                    // 主机名
	Cpu           string                 `protobuf:"bytes,5,opt,name=cpu,proto3" json:"cpu,omitempty"`                              // CPU 型号
	CpuCores      int32                  `protobuf:"varint,6,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`   // CPU 核心数
	MemoryGb      int32                  `protobuf:"varint,7,opt,name=memory_gb,json=memoryGb,proto3" json:"memory_gb,omitempty"`   // 内存大小（GB）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_pkg_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *SystemInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SystemInfo) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *SystemInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *SystemInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SystemInfo) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *SystemInfo) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *SystemInfo) GetMemoryGb() int32 {
	if x != nil {
		return x.MemoryGb
	}
	return 0
}

// NetworkInterface 网络接口信息
type NetworkInterface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`       // 网卡名称（如 eth0, ens192）
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`           // IP 地址
	Mask          string                 `protobuf:"bytes,3,opt,name=mask,proto3" json:"mask,omitempty"`       // 子网掩码
	Gateway       string                 `protobuf:"bytes,4,opt,name=gateway,proto3" json:"gateway,omitempty"` // 网关地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInterface) Reset() {
	*x = NetworkInterface{}
	mi := &file_pkg_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInterface) ProtoMessage() {}

func (x *NetworkInterface) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInterface.ProtoReflect.Descriptor instead.
func (*NetworkInterface) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *NetworkInterface) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkInterface) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *NetworkInterface) GetMask() string {
	if x != nil {
		return x.Mask
	}
	return ""
}

func (x *NetworkInterface) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

// AgentRegisterRequest Agent 注册请求
type AgentRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                               // Agent 名称
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`                           // 认证密钥
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                         // Agent 版本号
	SystemInfo    *SystemInfo            `protobuf:"bytes,4,opt,name=system_info,json=systemInfo,proto3" json:"system_info,omitempty"` // 系统信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRegisterRequest) Reset() {
	*x = AgentRegisterRequest{}
	mi := &file_pkg_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRegisterRequest) ProtoMessage() {}

func (x *AgentRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRegisterRequest.ProtoReflect.Descriptor instead.
func (*AgentRegisterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AgentRegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentRegisterRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *AgentRegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentRegisterRequest) GetSystemInfo() *SystemInfo {
	if x != nil {
		return x.SystemInfo
	}
	return nil
}

// AgentRegisterResponse Agent 注册响应
type AgentRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                     // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                      // 响应消息
	AgentId       uint64                 `protobuf:"varint,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`      // Agent ID（Headscale User ID）
	AuthKey       string                 `protobuf:"bytes,4,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"`       // Tailscale PreAuthKey，用于隧道连接
	ServerUrl     string                 `protobuf:"bytes,5,opt,name=server_url,json=serverUrl,proto3" json:"server_url,omitempty"` // Headscale 服务器地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRegisterResponse) Reset() {
	*x = AgentRegisterResponse{}
	mi := &file_pkg_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRegisterResponse) ProtoMessage() {}

func (x *AgentRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRegisterResponse.ProtoReflect.Descriptor instead.
func (*AgentRegisterResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AgentRegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AgentRegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AgentRegisterResponse) GetAgentId() uint64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *AgentRegisterResponse) GetAuthKey() string {
	if x != nil {
		return x.AuthKey
	}
	return ""
}

func (x *AgentRegisterResponse) GetServerUrl() string {
	if x != nil {
		return x.ServerUrl
	}
	return ""
}

// AgentAuthenticateRequest Agent 认证请求
type AgentAuthenticateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       uint64                 `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`         // Agent ID
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`                           // 认证密钥
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                         // Agent 版本号
	SystemInfo    *SystemInfo            `protobuf:"bytes,4,opt,name=system_info,json=systemInfo,proto3" json:"system_info,omitempty"` // 系统信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentAuthenticateRequest) Reset() {
	*x = AgentAuthenticateRequest{}
	mi := &file_pkg_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentAuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentAuthenticateRequest) ProtoMessage() {}

func (x *AgentAuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentAuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AgentAuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *AgentAuthenticateRequest) GetAgentId() uint64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *AgentAuthenticateRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *AgentAuthenticateRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentAuthenticateRequest) GetSystemInfo() *SystemInfo {
	if x != nil {
		return x.SystemInfo
	}
	return nil
}

// AgentAuthenticateResponse Agent 认证响应
type AgentAuthenticateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                     // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                      // 响应消息
	AuthKey       string                 `protobuf:"bytes,3,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"`       // Tailscale PreAuthKey（如需重新连接）
	ServerUrl     string                 `protobuf:"bytes,4,opt,name=server_url,json=serverUrl,proto3" json:"server_url,omitempty"` // Headscale 服务器地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentAuthenticateResponse) Reset() {
	*x = AgentAuthenticateResponse{}
	mi := &file_pkg_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentAuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentAuthenticateResponse) ProtoMessage() {}

func (x *AgentAuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentAuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AgentAuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *AgentAuthenticateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AgentAuthenticateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AgentAuthenticateResponse) GetAuthKey() string {
	if x != nil {
		return x.AuthKey
	}
	return ""
}

func (x *AgentAuthenticateResponse) GetServerUrl() string {
	if x != nil {
		return x.ServerUrl
	}
	return ""
}

// ServiceStatus 端口映射服务状态
type ServiceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"` // 服务 ID
	Running       bool                   `protobuf:"varint,2,opt,name=running,proto3" json:"running,omitempty"`                     // 是否运行中
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                          // 错误信息（如有）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceStatus) Reset() {
	*x = ServiceStatus{}
	mi := &file_pkg_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStatus) ProtoMessage() {}

func (x *ServiceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStatus.ProtoReflect.Descriptor instead.
func (*ServiceStatus) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ServiceStatus) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ServiceStatus) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *ServiceStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ForwardStatus 端口访问服务状态
type ForwardStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ForwardId     string                 `protobuf:"bytes,1,opt,name=forward_id,json=forwardId,proto3" json:"forward_id,omitempty"` // 端口访问 ID
	Running       bool                   `protobuf:"varint,2,opt,name=running,proto3" json:"running,omitempty"`                     // 是否运行中
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                          // 错误信息（如有）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardStatus) Reset() {
	*x = ForwardStatus{}
	mi := &file_pkg_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardStatus) ProtoMessage() {}

func (x *ForwardStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardStatus.ProtoReflect.Descriptor instead.
func (*ForwardStatus) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ForwardStatus) GetForwardId() string {
	if x != nil {
		return x.ForwardId
	}
	return ""
}

func (x *ForwardStatus) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *ForwardStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// AgentHeartbeatRequest Agent 心跳请求
type AgentHeartbeatRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentId         uint64                 `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                         // Agent ID
	TunnelIp        string                 `protobuf:"bytes,2,opt,name=tunnel_ip,json=tunnelIp,proto3" json:"tunnel_ip,omitempty"`                       // 隧道 IP
	TunnelConnected bool                   `protobuf:"varint,3,opt,name=tunnel_connected,json=tunnelConnected,proto3" json:"tunnel_connected,omitempty"` // 隧道连接状态
	ServiceStatus   []*ServiceStatus       `protobuf:"bytes,4,rep,name=service_status,json=serviceStatus,proto3" json:"service_status,omitempty"`        // 端口映射服务状态列表
	ForwardStatus   []*ForwardStatus       `protobuf:"bytes,5,rep,name=forward_status,json=forwardStatus,proto3" json:"forward_status,omitempty"`        // 端口访问服务状态列表
	// 网络信息（首次心跳或变更时上报）
	Hostname      string              `protobuf:"bytes,6,opt,name=hostname,proto3" json:"hostname,omitempty"` // 主机名
	Runtime       string              `protobuf:"bytes,7,opt,name=runtime,proto3" json:"runtime,omitempty"`   // 运行环境：docker / kubernetes / physical
	Networks      []*NetworkInterface `protobuf:"bytes,8,rep,name=networks,proto3" json:"networks,omitempty"` // 网络接口列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHeartbeatRequest) Reset() {
	*x = AgentHeartbeatRequest{}
	mi := &file_pkg_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHeartbeatRequest) ProtoMessage() {}

func (x *AgentHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*AgentHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *AgentHeartbeatRequest) GetAgentId() uint64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *AgentHeartbeatRequest) GetTunnelIp() string {
	if x != nil {
		return x.TunnelIp
	}
	return ""
}

func (x *AgentHeartbeatRequest) GetTunnelConnected() bool {
	if x != nil {
		return x.TunnelConnected
	}
	return false
}

func (x *AgentHeartbeatRequest) GetServiceStatus() []*ServiceStatus {
	if x != nil {
		return x.ServiceStatus
	}
	return nil
}

func (x *AgentHeartbeatRequest) GetForwardStatus() []*ForwardStatus {
	if x != nil {
		return x.ForwardStatus
	}
	return nil
}

func (x *AgentHeartbeatRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentHeartbeatRequest) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *AgentHeartbeatRequest) GetNetworks() []*NetworkInterface {
	if x != nil {
		return x.Networks
	}
	return nil
}

// ServiceConfig 端口映射配置
type ServiceConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                   // 服务 ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                               // 服务名称
	SourceAddr    string                 `protobuf:"bytes,3,opt,name=source_addr,json=sourceAddr,proto3" json:"source_addr,omitempty"` // 源地址（VPN IP:端口，如 100.64.0.1:80）
	TargetAddr    string                 `protobuf:"bytes,4,opt,name=target_addr,json=targetAddr,proto3" json:"target_addr,omitempty"` // 目标地址（局域网地址，如 192.168.1.10:80）
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`                        // 是否启用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceConfig) Reset() {
	*x = ServiceConfig{}
	mi := &file_pkg_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceConfig) ProtoMessage() {}

func (x *ServiceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceConfig.ProtoReflect.Descriptor instead.
func (*ServiceConfig) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ServiceConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceConfig) GetSourceAddr() string {
	if x != nil {
		return x.SourceAddr
	}
	return ""
}

func (x *ServiceConfig) GetTargetAddr() string {
	if x != nil {
		return x.TargetAddr
	}
	return ""
}

func (x *ServiceConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// ForwardConfig 端口访问配置
type ForwardConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                      // 端口访问 ID
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`       // 关联的目标服务 ID
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // 关联的目标服务名称
	SourceAddr    string                 `protobuf:"bytes,4,opt,name=source_addr,json=sourceAddr,proto3" json:"source_addr,omitempty"`    // 源地址（局域网 IP:端口，如 192.168.1.100:13306）
	TargetAddr    string                 `protobuf:"bytes,5,opt,name=target_addr,json=targetAddr,proto3" json:"target_addr,omitempty"`    // 目标地址（VPN 地址，如 100.64.0.1:3306）
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`                           // 是否启用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardConfig) Reset() {
	*x = ForwardConfig{}
	mi := &file_pkg_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardConfig) ProtoMessage() {}

func (x *ForwardConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardConfig.ProtoReflect.Descriptor instead.
func (*ForwardConfig) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ForwardConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ForwardConfig) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ForwardConfig) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ForwardConfig) GetSourceAddr() string {
	if x != nil {
		return x.SourceAddr
	}
	return ""
}

func (x *ForwardConfig) GetTargetAddr() string {
	if x != nil {
		return x.TargetAddr
	}
	return ""
}

func (x *ForwardConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// AgentHeartbeatResponse Agent 心跳响应
type AgentHeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigVersion int64                  `protobuf:"varint,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"` // 配置版本号
	Services      []*ServiceConfig       `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`                                 // 端口映射配置（如有变更）
	Forwards      []*ForwardConfig       `protobuf:"bytes,3,rep,name=forwards,proto3" json:"forwards,omitempty"`                                 // 端口访问配置（如有变更）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHeartbeatResponse) Reset() {
	*x = AgentHeartbeatResponse{}
	mi := &file_pkg_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHeartbeatResponse) ProtoMessage() {}

func (x *AgentHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*AgentHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *AgentHeartbeatResponse) GetConfigVersion() int64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *AgentHeartbeatResponse) GetServices() []*ServiceConfig {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *AgentHeartbeatResponse) GetForwards() []*ForwardConfig {
	if x != nil {
		return x.Forwards
	}
	return nil
}

// GetRealtimeStatusRequest 获取实时状态请求
type GetRealtimeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       uint64                 `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // Agent ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRealtimeStatusRequest) Reset() {
	*x = GetRealtimeStatusRequest{}
	mi := &file_pkg_proto_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRealtimeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRealtimeStatusRequest) ProtoMessage() {}

func (x *GetRealtimeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRealtimeStatusRequest.ProtoReflect.Descriptor instead.
func (*GetRealtimeStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{12}
}

func (x *GetRealtimeStatusRequest) GetAgentId() uint64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

// GetRealtimeStatusResponse 获取实时状态响应
type GetRealtimeStatusResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Hostname            string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`                                                     // 主机名
	Runtime             string                 `protobuf:"bytes,2,opt,name=runtime,proto3" json:"runtime,omitempty"`                                                       // 运行环境：docker / k8s / vm / physical
	Networks            []*NetworkInterface    `protobuf:"bytes,3,rep,name=networks,proto3" json:"networks,omitempty"`                                                     // 网络接口列表
	TunnelIp            string                 `protobuf:"bytes,4,opt,name=tunnel_ip,json=tunnelIp,proto3" json:"tunnel_ip,omitempty"`                                     // 隧道 IP
	TunnelConnected     bool                   `protobuf:"varint,5,opt,name=tunnel_connected,json=tunnelConnected,proto3" json:"tunnel_connected,omitempty"`               // 隧道连接状态
	TunnelConnectedTime int64                  `protobuf:"varint,6,opt,name=tunnel_connected_time,json=tunnelConnectedTime,proto3" json:"tunnel_connected_time,omitempty"` // 隧道连接时间（Unix 时间戳）
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetRealtimeStatusResponse) Reset() {
	*x = GetRealtimeStatusResponse{}
	mi := &file_pkg_proto_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRealtimeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRealtimeStatusResponse) ProtoMessage() {}

func (x *GetRealtimeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRealtimeStatusResponse.ProtoReflect.Descriptor instead.
func (*GetRealtimeStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{13}
}

func (x *GetRealtimeStatusResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *GetRealtimeStatusResponse) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *GetRealtimeStatusResponse) GetNetworks() []*NetworkInterface {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *GetRealtimeStatusResponse) GetTunnelIp() string {
	if x != nil {
		return x.TunnelIp
	}
	return ""
}

func (x *GetRealtimeStatusResponse) GetTunnelConnected() bool {
	if x != nil {
		return x.TunnelConnected
	}
	return false
}

func (x *GetRealtimeStatusResponse) GetTunnelConnectedTime() int64 {
	if x != nil {
		return x.TunnelConnectedTime
	}
	return 0
}

// ProxyStatus 本地服务状态
type ProxyStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"` // 服务 ID
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                        // 状态：running/disabled/error/pending
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"` // 错误代码
	ErrorMsg      string                 `protobuf:"bytes,4,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`    // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyStatus) Reset() {
	*x = ProxyStatus{}
	mi := &file_pkg_proto_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyStatus) ProtoMessage() {}

func (x *ProxyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyStatus.ProtoReflect.Descriptor instead.
func (*ProxyStatus) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{14}
}

func (x *ProxyStatus) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ProxyStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProxyStatus) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ProxyStatus) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

// ReportProxyStatusRequest 上报本地服务状态请求
type ReportProxyStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       uint64                 `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // Agent ID
	Statuses      []*ProxyStatus         `protobuf:"bytes,2,rep,name=statuses,proto3" json:"statuses,omitempty"`               // 状态列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportProxyStatusRequest) Reset() {
	*x = ReportProxyStatusRequest{}
	mi := &file_pkg_proto_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportProxyStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportProxyStatusRequest) ProtoMessage() {}

func (x *ReportProxyStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportProxyStatusRequest.ProtoReflect.Descriptor instead.
func (*ReportProxyStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{15}
}

func (x *ReportProxyStatusRequest) GetAgentId() uint64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *ReportProxyStatusRequest) GetStatuses() []*ProxyStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

// ReportProxyStatusResponse 上报本地服务状态响应
type ReportProxyStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportProxyStatusResponse) Reset() {
	*x = ReportProxyStatusResponse{}
	mi := &file_pkg_proto_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportProxyStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportProxyStatusResponse) ProtoMessage() {}

func (x *ReportProxyStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportProxyStatusResponse.ProtoReflect.Descriptor instead.
func (*ReportProxyStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{16}
}

func (x *ReportProxyStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportProxyStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// VisitorStatus 远程服务状态
type VisitorStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ForwardId      string                 `protobuf:"bytes,1,opt,name=forward_id,json=forwardId,proto3" json:"forward_id,omitempty"`                // 远程服务 ID
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                       // 状态：running/disabled/error/pending
	ConfiguredAddr string                 `protobuf:"bytes,3,opt,name=configured_addr,json=configuredAddr,proto3" json:"configured_addr,omitempty"` // 配置的源地址
	ActualAddr     string                 `protobuf:"bytes,4,opt,name=actual_addr,json=actualAddr,proto3" json:"actual_addr,omitempty"`             // 实际使用的源地址
	IpChanged      bool                   `protobuf:"varint,5,opt,name=ip_changed,json=ipChanged,proto3" json:"ip_changed,omitempty"`               // IP 是否变化
	ChangeReason   string                 `protobuf:"bytes,6,opt,name=change_reason,json=changeReason,proto3" json:"change_reason,omitempty"`       // 变化原因：DHCP_IP_CHANGE / NETWORK_INTERFACE_LOST
	ErrorCode      string                 `protobuf:"bytes,7,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`                // 错误代码
	ErrorMsg       string                 `protobuf:"bytes,8,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`                   // 错误信息
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VisitorStatus) Reset() {
	*x = VisitorStatus{}
	mi := &file_pkg_proto_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitorStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitorStatus) ProtoMessage() {}

func (x *VisitorStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitorStatus.ProtoReflect.Descriptor instead.
func (*VisitorStatus) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{17}
}

func (x *VisitorStatus) GetForwardId() string {
	if x != nil {
		return x.ForwardId
	}
	return ""
}

func (x *VisitorStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VisitorStatus) GetConfiguredAddr() string {
	if x != nil {
		return x.ConfiguredAddr
	}
	return ""
}

func (x *VisitorStatus) GetActualAddr() string {
	if x != nil {
		return x.ActualAddr
	}
	return ""
}

func (x *VisitorStatus) GetIpChanged() bool {
	if x != nil {
		return x.IpChanged
	}
	return false
}

func (x *VisitorStatus) GetChangeReason() string {
	if x != nil {
		return x.ChangeReason
	}
	return ""
}

func (x *VisitorStatus) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *VisitorStatus) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

// ReportVisitorStatusRequest 上报远程服务状态请求
type ReportVisitorStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       uint64                 `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // Agent ID
	Statuses      []*VisitorStatus       `protobuf:"bytes,2,rep,name=statuses,proto3" json:"statuses,omitempty"`               // 状态列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportVisitorStatusRequest) Reset() {
	*x = ReportVisitorStatusRequest{}
	mi := &file_pkg_proto_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportVisitorStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportVisitorStatusRequest) ProtoMessage() {}

func (x *ReportVisitorStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportVisitorStatusRequest.ProtoReflect.Descriptor instead.
func (*ReportVisitorStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{18}
}

func (x *ReportVisitorStatusRequest) GetAgentId() uint64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *ReportVisitorStatusRequest) GetStatuses() []*VisitorStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

// ReportVisitorStatusResponse 上报远程服务状态响应
type ReportVisitorStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportVisitorStatusResponse) Reset() {
	*x = ReportVisitorStatusResponse{}
	mi := &file_pkg_proto_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportVisitorStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportVisitorStatusResponse) ProtoMessage() {}

func (x *ReportVisitorStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportVisitorStatusResponse.ProtoReflect.Descriptor instead.
func (*ReportVisitorStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{19}
}

func (x *ReportVisitorStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportVisitorStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ReportNetworkChangeRequest 上报网络变化请求
type ReportNetworkChangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       uint64                 `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // Agent ID
	Networks      []*NetworkInterface    `protobuf:"bytes,2,rep,name=networks,proto3" json:"networks,omitempty"`               // 新的网络接口列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportNetworkChangeRequest) Reset() {
	*x = ReportNetworkChangeRequest{}
	mi := &file_pkg_proto_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportNetworkChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportNetworkChangeRequest) ProtoMessage() {}

func (x *ReportNetworkChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportNetworkChangeRequest.ProtoReflect.Descriptor instead.
func (*ReportNetworkChangeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{20}
}

func (x *ReportNetworkChangeRequest) GetAgentId() uint64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *ReportNetworkChangeRequest) GetNetworks() []*NetworkInterface {
	if x != nil {
		return x.Networks
	}
	return nil
}

// ReportNetworkChangeResponse 上报网络变化响应
type ReportNetworkChangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportNetworkChangeResponse) Reset() {
	*x = ReportNetworkChangeResponse{}
	mi := &file_pkg_proto_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportNetworkChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportNetworkChangeResponse) ProtoMessage() {}

func (x *ReportNetworkChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportNetworkChangeResponse.ProtoReflect.Descriptor instead.
func (*ReportNetworkChangeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{21}
}

func (x *ReportNetworkChangeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportNetworkChangeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_proto_agent_proto protoreflect.FileDescriptor

const file_pkg_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x15pkg/proto/agent.proto\x12\x12awecloud.signaling\"\xb7\x01\n" +
	"\n" +
	"SystemInfo\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x1d\n" +
	"\n" +
	"os_version\x18\x02 \x01(\tR\tosVersion\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\x12\x10\n" +
	"\x03cpu\x18\x05 \x01(\tR\x03cpu\x12\x1b\n" +
	"\tcpu_cores\x18\x06 \x01(\x05R\bcpuCores\x12\x1b\n" +
	"\tmemory_gb\x18\a \x01(\x05R\bmemoryGb\"d\n" +
	"\x10NetworkInterface\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x12\n" +
	"\x04mask\x18\x03 \x01(\tR\x04mask\x12\x18\n" +
	"\agateway\x18\x04 \x01(\tR\agateway\"\x9d\x01\n" +
	"\x14AgentRegisterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12?\n" +
	"\vsystem_info\x18\x04 \x01(\v2\x1e.awecloud.signaling.SystemInfoR\n" +
	"systemInfo\"\xa0\x01\n" +
	"\x15AgentRegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\x04R\aagentId\x12\x19\n" +
	"\bauth_key\x18\x04 \x01(\tR\aauthKey\x12\x1d\n" +
	"\n" +
	"server_url\x18\x05 \x01(\tR\tserverUrl\"\xa8\x01\n" +
	"\x18AgentAuthenticateRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x04R\aagentId\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12?\n" +
	"\vsystem_info\x18\x04 \x01(\v2\x1e.awecloud.signaling.SystemInfoR\n" +
	"systemInfo\"\x89\x01\n" +
	"\x19AgentAuthenticateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bauth_key\x18\x03 \x01(\tR\aauthKey\x12\x1d\n" +
	"\n" +
	"server_url\x18\x04 \x01(\tR\tserverUrl\"^\n" +
	"\rServiceStatus\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x18\n" +
	"\arunning\x18\x02 \x01(\bR\arunning\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"^\n" +
	"\rForwardStatus\x12\x1d\n" +
	"\n" +
	"forward_id\x18\x01 \x01(\tR\tforwardId\x12\x18\n" +
	"\arunning\x18\x02 \x01(\bR\arunning\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x86\x03\n" +
	"\x15AgentHeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x04R\aagentId\x12\x1b\n" +
	"\ttunnel_ip\x18\x02 \x01(\tR\btunnelIp\x12)\n" +
	"\x10tunnel_connected\x18\x03 \x01(\bR\x0ftunnelConnected\x12H\n" +
	"\x0eservice_status\x18\x04 \x03(\v2!.awecloud.signaling.ServiceStatusR\rserviceStatus\x12H\n" +
	"\x0eforward_status\x18\x05 \x03(\v2!.awecloud.signaling.ForwardStatusR\rforwardStatus\x12\x1a\n" +
	"\bhostname\x18\x06 \x01(\tR\bhostname\x12\x18\n" +
	"\aruntime\x18\a \x01(\tR\aruntime\x12@\n" +
	"\bnetworks\x18\b \x03(\v2$.awecloud.signaling.NetworkInterfaceR\bnetworks\"\x8f\x01\n" +
	"\rServiceConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vsource_addr\x18\x03 \x01(\tR\n" +
	"sourceAddr\x12\x1f\n" +
	"\vtarget_addr\x18\x04 \x01(\tR\n" +
	"targetAddr\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\"\xbd\x01\n" +
	"\rForwardConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vsource_addr\x18\x04 \x01(\tR\n" +
	"sourceAddr\x12\x1f\n" +
	"\vtarget_addr\x18\x05 \x01(\tR\n" +
	"targetAddr\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\"\xbd\x01\n" +
	"\x16AgentHeartbeatResponse\x12%\n" +
	"\x0econfig_version\x18\x01 \x01(\x03R\rconfigVersion\x12=\n" +
	"\bservices\x18\x02 \x03(\v2!.awecloud.signaling.ServiceConfigR\bservices\x12=\n" +
	"\bforwards\x18\x03 \x03(\v2!.awecloud.signaling.ForwardConfigR\bforwards\"5\n" +
	"\x18GetRealtimeStatusRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x04R\aagentId\"\x8f\x02\n" +
	"\x19GetRealtimeStatusResponse\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x18\n" +
	"\aruntime\x18\x02 \x01(\tR\aruntime\x12@\n" +
	"\bnetworks\x18\x03 \x03(\v2$.awecloud.signaling.NetworkInterfaceR\bnetworks\x12\x1b\n" +
	"\ttunnel_ip\x18\x04 \x01(\tR\btunnelIp\x12)\n" +
	"\x10tunnel_connected\x18\x05 \x01(\bR\x0ftunnelConnected\x122\n" +
	"\x15tunnel_connected_time\x18\x06 \x01(\x03R\x13tunnelConnectedTime\"\x80\x01\n" +
	"\vProxyStatus\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12\x1b\n" +
	"\terror_msg\x18\x04 \x01(\tR\berrorMsg\"r\n" +
	"\x18ReportProxyStatusRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x04R\aagentId\x12;\n" +
	"\bstatuses\x18\x02 \x03(\v2\x1f.awecloud.signaling.ProxyStatusR\bstatuses\"O\n" +
	"\x19ReportProxyStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x90\x02\n" +
	"\rVisitorStatus\x12\x1d\n" +
	"\n" +
	"forward_id\x18\x01 \x01(\tR\tforwardId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12'\n" +
	"\x0fconfigured_addr\x18\x03 \x01(\tR\x0econfiguredAddr\x12\x1f\n" +
	"\vactual_addr\x18\x04 \x01(\tR\n" +
	"actualAddr\x12\x1d\n" +
	"\n" +
	"ip_changed\x18\x05 \x01(\bR\tipChanged\x12#\n" +
	"\rchange_reason\x18\x06 \x01(\tR\fchangeReason\x12\x1d\n" +
	"\n" +
	"error_code\x18\a \x01(\tR\terrorCode\x12\x1b\n" +
	"\terror_msg\x18\b \x01(\tR\berrorMsg\"v\n" +
	"\x1aReportVisitorStatusRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x04R\aagentId\x12=\n" +
	"\bstatuses\x18\x02 \x03(\v2!.awecloud.signaling.VisitorStatusR\bstatuses\"Q\n" +
	"\x1bReportVisitorStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"y\n" +
	"\x1aReportNetworkChangeRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x04R\aagentId\x12@\n" +
	"\bnetworks\x18\x02 \x03(\v2$.awecloud.signaling.NetworkInterfaceR\bnetworks\"Q\n" +
	"\x1bReportNetworkChangeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x98\x06\n" +
	"\fAgentService\x12_\n" +
	"\bRegister\x12(.awecloud.signaling.AgentRegisterRequest\x1a).awecloud.signaling.AgentRegisterResponse\x12k\n" +
	"\fAuthenticate\x12,.awecloud.signaling.AgentAuthenticateRequest\x1a-.awecloud.signaling.AgentAuthenticateResponse\x12f\n" +
	"\tHeartbeat\x12).awecloud.signaling.AgentHeartbeatRequest\x1a*.awecloud.signaling.AgentHeartbeatResponse(\x010\x01\x12p\n" +
	"\x11GetRealtimeStatus\x12,.awecloud.signaling.GetRealtimeStatusRequest\x1a-.awecloud.signaling.GetRealtimeStatusResponse\x12p\n" +
	"\x11ReportProxyStatus\x12,.awecloud.signaling.ReportProxyStatusRequest\x1a-.awecloud.signaling.ReportProxyStatusResponse\x12v\n" +
	"\x13ReportVisitorStatus\x12..awecloud.signaling.ReportVisitorStatusRequest\x1a/.awecloud.signaling.ReportVisitorStatusResponse\x12v\n" +
	"\x13ReportNetworkChange\x12..awecloud.signaling.ReportNetworkChangeRequest\x1a/.awecloud.signaling.ReportNetworkChangeResponseB<Z:github.com/open-beagle/awecloud-signaling-server/pkg/protob\x06proto3"

var (
	file_pkg_proto_agent_proto_rawDescOnce sync.Once
	file_pkg_proto_agent_proto_rawDescData []byte
)

func file_pkg_proto_agent_proto_rawDescGZIP() []byte {
	file_pkg_proto_agent_proto_rawDescOnce.Do(func() {
		file_pkg_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_agent_proto_rawDesc), len(file_pkg_proto_agent_proto_rawDesc)))
	})
	return file_pkg_proto_agent_proto_rawDescData
}

var file_pkg_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_pkg_proto_agent_proto_goTypes = []any{
	(*SystemInfo)(nil),                  // 0: awecloud.signaling.SystemInfo
	(*NetworkInterface)(nil),            // 1: awecloud.signaling.NetworkInterface
	(*AgentRegisterRequest)(nil),        // 2: awecloud.signaling.AgentRegisterRequest
	(*AgentRegisterResponse)(nil),       // 3: awecloud.signaling.AgentRegisterResponse
	(*AgentAuthenticateRequest)(nil),    // 4: awecloud.signaling.AgentAuthenticateRequest
	(*AgentAuthenticateResponse)(nil),   // 5: awecloud.signaling.AgentAuthenticateResponse
	(*ServiceStatus)(nil),               // 6: awecloud.signaling.ServiceStatus
	(*ForwardStatus)(nil),               // 7: awecloud.signaling.ForwardStatus
	(*AgentHeartbeatRequest)(nil),       // 8: awecloud.signaling.AgentHeartbeatRequest
	(*ServiceConfig)(nil),               // 9: awecloud.signaling.ServiceConfig
	(*ForwardConfig)(nil),               // 10: awecloud.signaling.ForwardConfig
	(*AgentHeartbeatResponse)(nil),      // 11: awecloud.signaling.AgentHeartbeatResponse
	(*GetRealtimeStatusRequest)(nil),    // 12: awecloud.signaling.GetRealtimeStatusRequest
	(*GetRealtimeStatusResponse)(nil),   // 13: awecloud.signaling.GetRealtimeStatusResponse
	(*ProxyStatus)(nil),                 // 14: awecloud.signaling.ProxyStatus
	(*ReportProxyStatusRequest)(nil),    // 15: awecloud.signaling.ReportProxyStatusRequest
	(*ReportProxyStatusResponse)(nil),   // 16: awecloud.signaling.ReportProxyStatusResponse
	(*VisitorStatus)(nil),               // 17: awecloud.signaling.VisitorStatus
	(*ReportVisitorStatusRequest)(nil),  // 18: awecloud.signaling.ReportVisitorStatusRequest
	(*ReportVisitorStatusResponse)(nil), // 19: awecloud.signaling.ReportVisitorStatusResponse
	(*ReportNetworkChangeRequest)(nil),  // 20: awecloud.signaling.ReportNetworkChangeRequest
	(*ReportNetworkChangeResponse)(nil), // 21: awecloud.signaling.ReportNetworkChangeResponse
}
var file_pkg_proto_agent_proto_depIdxs = []int32{
	0,  // 0: awecloud.signaling.AgentRegisterRequest.system_info:type_name -> awecloud.signaling.SystemInfo
	0,  // 1: awecloud.signaling.AgentAuthenticateRequest.system_info:type_name -> awecloud.signaling.SystemInfo
	6,  // 2: awecloud.signaling.AgentHeartbeatRequest.service_status:type_name -> awecloud.signaling.ServiceStatus
	7,  // 3: awecloud.signaling.AgentHeartbeatRequest.forward_status:type_name -> awecloud.signaling.ForwardStatus
	1,  // 4: awecloud.signaling.AgentHeartbeatRequest.networks:type_name -> awecloud.signaling.NetworkInterface
	9,  // 5: awecloud.signaling.AgentHeartbeatResponse.services:type_name -> awecloud.signaling.ServiceConfig
	10, // 6: awecloud.signaling.AgentHeartbeatResponse.forwards:type_name -> awecloud.signaling.ForwardConfig
	1,  // 7: awecloud.signaling.GetRealtimeStatusResponse.networks:type_name -> awecloud.signaling.NetworkInterface
	14, // 8: awecloud.signaling.ReportProxyStatusRequest.statuses:type_name -> awecloud.signaling.ProxyStatus
	17, // 9: awecloud.signaling.ReportVisitorStatusRequest.statuses:type_name -> awecloud.signaling.VisitorStatus
	1,  // 10: awecloud.signaling.ReportNetworkChangeRequest.networks:type_name -> awecloud.signaling.NetworkInterface
	2,  // 11: awecloud.signaling.AgentService.Register:input_type -> awecloud.signaling.AgentRegisterRequest
	4,  // 12: awecloud.signaling.AgentService.Authenticate:input_type -> awecloud.signaling.AgentAuthenticateRequest
	8,  // 13: awecloud.signaling.AgentService.Heartbeat:input_type -> awecloud.signaling.AgentHeartbeatRequest
	12, // 14: awecloud.signaling.AgentService.GetRealtimeStatus:input_type -> awecloud.signaling.GetRealtimeStatusRequest
	15, // 15: awecloud.signaling.AgentService.ReportProxyStatus:input_type -> awecloud.signaling.ReportProxyStatusRequest
	18, // 16: awecloud.signaling.AgentService.ReportVisitorStatus:input_type -> awecloud.signaling.ReportVisitorStatusRequest
	20, // 17: awecloud.signaling.AgentService.ReportNetworkChange:input_type -> awecloud.signaling.ReportNetworkChangeRequest
	3,  // 18: awecloud.signaling.AgentService.Register:output_type -> awecloud.signaling.AgentRegisterResponse
	5,  // 19: awecloud.signaling.AgentService.Authenticate:output_type -> awecloud.signaling.AgentAuthenticateResponse
	11, // 20: awecloud.signaling.AgentService.Heartbeat:output_type -> awecloud.signaling.AgentHeartbeatResponse
	13, // 21: awecloud.signaling.AgentService.GetRealtimeStatus:output_type -> awecloud.signaling.GetRealtimeStatusResponse
	16, // 22: awecloud.signaling.AgentService.ReportProxyStatus:output_type -> awecloud.signaling.ReportProxyStatusResponse
	19, // 23: awecloud.signaling.AgentService.ReportVisitorStatus:output_type -> awecloud.signaling.ReportVisitorStatusResponse
	21, // 24: awecloud.signaling.AgentService.ReportNetworkChange:output_type -> awecloud.signaling.ReportNetworkChangeResponse
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pkg_proto_agent_proto_init() }
func file_pkg_proto_agent_proto_init() {
	if File_pkg_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_agent_proto_rawDesc), len(file_pkg_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_agent_proto_goTypes,
		DependencyIndexes: file_pkg_proto_agent_proto_depIdxs,
		MessageInfos:      file_pkg_proto_agent_proto_msgTypes,
	}.Build()
	File_pkg_proto_agent_proto = out.File
	file_pkg_proto_agent_proto_goTypes = nil
	file_pkg_proto_agent_proto_depIdxs = nil
}
