// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: pkg/proto/agent.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command_Type int32

const (
	Command_CREATE_STCP Command_Type = 0
	Command_DELETE_STCP Command_Type = 1
	Command_CREATE_TCP  Command_Type = 2
	Command_DELETE_TCP  Command_Type = 3
)

// Enum value maps for Command_Type.
var (
	Command_Type_name = map[int32]string{
		0: "CREATE_STCP",
		1: "DELETE_STCP",
		2: "CREATE_TCP",
		3: "DELETE_TCP",
	}
	Command_Type_value = map[string]int32{
		"CREATE_STCP": 0,
		"DELETE_STCP": 1,
		"CREATE_TCP":  2,
		"DELETE_TCP":  3,
	}
)

func (x Command_Type) Enum() *Command_Type {
	p := new(Command_Type)
	*p = x
	return p
}

func (x Command_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_agent_proto_enumTypes[0].Descriptor()
}

func (Command_Type) Type() protoreflect.EnumType {
	return &file_pkg_proto_agent_proto_enumTypes[0]
}

func (x Command_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command_Type.Descriptor instead.
func (Command_Type) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{4, 0}
}

// Agent注册请求
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentName     string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	AgentToken    string                 `protobuf:"bytes,2,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_pkg_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *RegisterRequest) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

// Agent注册响应
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AgentId       int64                  `protobuf:"varint,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`   // 隧道认证 Token
	Server        string                 `protobuf:"bytes,5,opt,name=server,proto3" json:"server,omitempty"` // 隧道服务器地址（完整 URL 或空）
	Port          int32                  `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`    // 隧道服务器端口（使用 URL 时为 0）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_pkg_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *RegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterResponse) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *RegisterResponse) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// Agent心跳请求
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       int64                  `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentToken    string                 `protobuf:"bytes,2,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_pkg_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *HeartbeatRequest) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

// Agent心跳响应
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_pkg_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Server指令
type Command struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Type      Command_Type           `protobuf:"varint,2,opt,name=type,proto3,enum=awecloud.signaling.Command_Type" json:"type,omitempty"`
	// STCP相关字段
	InstanceName string `protobuf:"bytes,3,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	SecretKey    string `protobuf:"bytes,4,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	// TCP相关字段
	ServiceName string `protobuf:"bytes,5,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	RemotePort  int32  `protobuf:"varint,6,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	// 公共字段
	LocalIp       string `protobuf:"bytes,7,opt,name=local_ip,json=localIp,proto3" json:"local_ip,omitempty"`
	LocalPort     int32  `protobuf:"varint,8,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_pkg_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Command) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Command) GetType() Command_Type {
	if x != nil {
		return x.Type
	}
	return Command_CREATE_STCP
}

func (x *Command) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *Command) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *Command) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Command) GetRemotePort() int32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

func (x *Command) GetLocalIp() string {
	if x != nil {
		return x.LocalIp
	}
	return ""
}

func (x *Command) GetLocalPort() int32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

// 指令响应
type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_pkg_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *CommandResponse) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 状态上报
type StatusReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       int64                  `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	StcpStatuses  []*STCPStatus          `protobuf:"bytes,2,rep,name=stcp_statuses,json=stcpStatuses,proto3" json:"stcp_statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReport) Reset() {
	*x = StatusReport{}
	mi := &file_pkg_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReport) ProtoMessage() {}

func (x *StatusReport) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReport.ProtoReflect.Descriptor instead.
func (*StatusReport) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *StatusReport) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *StatusReport) GetStcpStatuses() []*STCPStatus {
	if x != nil {
		return x.StcpStatuses
	}
	return nil
}

type STCPStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	InstanceName      string                 `protobuf:"bytes,1,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	Status            string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "running", "stopped", "error"
	ActiveConnections int32                  `protobuf:"varint,3,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *STCPStatus) Reset() {
	*x = STCPStatus{}
	mi := &file_pkg_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *STCPStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*STCPStatus) ProtoMessage() {}

func (x *STCPStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use STCPStatus.ProtoReflect.Descriptor instead.
func (*STCPStatus) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *STCPStatus) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *STCPStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *STCPStatus) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

// 状态响应
type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_pkg_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *StatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 获取TCP服务请求
type GetTCPServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       int64                  `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTCPServicesRequest) Reset() {
	*x = GetTCPServicesRequest{}
	mi := &file_pkg_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTCPServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTCPServicesRequest) ProtoMessage() {}

func (x *GetTCPServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTCPServicesRequest.ProtoReflect.Descriptor instead.
func (*GetTCPServicesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *GetTCPServicesRequest) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

// TCP实例信息
type TCPServiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	LocalIp       string                 `protobuf:"bytes,2,opt,name=local_ip,json=localIp,proto3" json:"local_ip,omitempty"`
	LocalPort     int32                  `protobuf:"varint,3,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	RemotePort    int32                  `protobuf:"varint,4,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TCPServiceInfo) Reset() {
	*x = TCPServiceInfo{}
	mi := &file_pkg_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TCPServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCPServiceInfo) ProtoMessage() {}

func (x *TCPServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCPServiceInfo.ProtoReflect.Descriptor instead.
func (*TCPServiceInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *TCPServiceInfo) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *TCPServiceInfo) GetLocalIp() string {
	if x != nil {
		return x.LocalIp
	}
	return ""
}

func (x *TCPServiceInfo) GetLocalPort() int32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

func (x *TCPServiceInfo) GetRemotePort() int32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

// 获取TCP服务响应
type GetTCPServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Services      []*TCPServiceInfo      `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTCPServicesResponse) Reset() {
	*x = GetTCPServicesResponse{}
	mi := &file_pkg_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTCPServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTCPServicesResponse) ProtoMessage() {}

func (x *GetTCPServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTCPServicesResponse.ProtoReflect.Descriptor instead.
func (*GetTCPServicesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *GetTCPServicesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetTCPServicesResponse) GetServices() []*TCPServiceInfo {
	if x != nil {
		return x.Services
	}
	return nil
}

var File_pkg_proto_agent_proto protoreflect.FileDescriptor

const file_pkg_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x15pkg/proto/agent.proto\x12\x12awecloud.signaling\"Q\n" +
	"\x0fRegisterRequest\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12\x1f\n" +
	"\vagent_token\x18\x02 \x01(\tR\n" +
	"agentToken\"\xa3\x01\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\x03R\aagentId\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x12\x16\n" +
	"\x06server\x18\x05 \x01(\tR\x06server\x12\x12\n" +
	"\x04port\x18\x06 \x01(\x05R\x04port\"N\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x03R\aagentId\x12\x1f\n" +
	"\vagent_token\x18\x02 \x01(\tR\n" +
	"agentToken\"K\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"\xea\x02\n" +
	"\aCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x124\n" +
	"\x04type\x18\x02 \x01(\x0e2 .awecloud.signaling.Command.TypeR\x04type\x12#\n" +
	"\rinstance_name\x18\x03 \x01(\tR\finstanceName\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x04 \x01(\tR\tsecretKey\x12!\n" +
	"\fservice_name\x18\x05 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vremote_port\x18\x06 \x01(\x05R\n" +
	"remotePort\x12\x19\n" +
	"\blocal_ip\x18\a \x01(\tR\alocalIp\x12\x1d\n" +
	"\n" +
	"local_port\x18\b \x01(\x05R\tlocalPort\"H\n" +
	"\x04Type\x12\x0f\n" +
	"\vCREATE_STCP\x10\x00\x12\x0f\n" +
	"\vDELETE_STCP\x10\x01\x12\x0e\n" +
	"\n" +
	"CREATE_TCP\x10\x02\x12\x0e\n" +
	"\n" +
	"DELETE_TCP\x10\x03\"d\n" +
	"\x0fCommandResponse\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"n\n" +
	"\fStatusReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x03R\aagentId\x12C\n" +
	"\rstcp_statuses\x18\x02 \x03(\v2\x1e.awecloud.signaling.STCPStatusR\fstcpStatuses\"x\n" +
	"\n" +
	"STCPStatus\x12#\n" +
	"\rinstance_name\x18\x01 \x01(\tR\finstanceName\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12-\n" +
	"\x12active_connections\x18\x03 \x01(\x05R\x11activeConnections\"*\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"2\n" +
	"\x15GetTCPServicesRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x03R\aagentId\"\x8e\x01\n" +
	"\x0eTCPServiceInfo\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x19\n" +
	"\blocal_ip\x18\x02 \x01(\tR\alocalIp\x12\x1d\n" +
	"\n" +
	"local_port\x18\x03 \x01(\x05R\tlocalPort\x12\x1f\n" +
	"\vremote_port\x18\x04 \x01(\x05R\n" +
	"remotePort\"r\n" +
	"\x16GetTCPServicesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12>\n" +
	"\bservices\x18\x02 \x03(\v2\".awecloud.signaling.TCPServiceInfoR\bservices2\xde\x03\n" +
	"\fAgentService\x12U\n" +
	"\bRegister\x12#.awecloud.signaling.RegisterRequest\x1a$.awecloud.signaling.RegisterResponse\x12X\n" +
	"\tHeartbeat\x12$.awecloud.signaling.HeartbeatRequest\x1a%.awecloud.signaling.HeartbeatResponse\x12W\n" +
	"\x0fReceiveCommands\x12#.awecloud.signaling.CommandResponse\x1a\x1b.awecloud.signaling.Command(\x010\x01\x12T\n" +
	"\fReportStatus\x12 .awecloud.signaling.StatusReport\x1a\".awecloud.signaling.StatusResponse\x12n\n" +
	"\x15GetEnabledTCPServices\x12).awecloud.signaling.GetTCPServicesRequest\x1a*.awecloud.signaling.GetTCPServicesResponseB<Z:github.com/open-beagle/awecloud-signaling-server/pkg/protob\x06proto3"

var (
	file_pkg_proto_agent_proto_rawDescOnce sync.Once
	file_pkg_proto_agent_proto_rawDescData []byte
)

func file_pkg_proto_agent_proto_rawDescGZIP() []byte {
	file_pkg_proto_agent_proto_rawDescOnce.Do(func() {
		file_pkg_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_agent_proto_rawDesc), len(file_pkg_proto_agent_proto_rawDesc)))
	})
	return file_pkg_proto_agent_proto_rawDescData
}

var file_pkg_proto_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pkg_proto_agent_proto_goTypes = []any{
	(Command_Type)(0),              // 0: awecloud.signaling.Command.Type
	(*RegisterRequest)(nil),        // 1: awecloud.signaling.RegisterRequest
	(*RegisterResponse)(nil),       // 2: awecloud.signaling.RegisterResponse
	(*HeartbeatRequest)(nil),       // 3: awecloud.signaling.HeartbeatRequest
	(*HeartbeatResponse)(nil),      // 4: awecloud.signaling.HeartbeatResponse
	(*Command)(nil),                // 5: awecloud.signaling.Command
	(*CommandResponse)(nil),        // 6: awecloud.signaling.CommandResponse
	(*StatusReport)(nil),           // 7: awecloud.signaling.StatusReport
	(*STCPStatus)(nil),             // 8: awecloud.signaling.STCPStatus
	(*StatusResponse)(nil),         // 9: awecloud.signaling.StatusResponse
	(*GetTCPServicesRequest)(nil),  // 10: awecloud.signaling.GetTCPServicesRequest
	(*TCPServiceInfo)(nil),         // 11: awecloud.signaling.TCPServiceInfo
	(*GetTCPServicesResponse)(nil), // 12: awecloud.signaling.GetTCPServicesResponse
}
var file_pkg_proto_agent_proto_depIdxs = []int32{
	0,  // 0: awecloud.signaling.Command.type:type_name -> awecloud.signaling.Command.Type
	8,  // 1: awecloud.signaling.StatusReport.stcp_statuses:type_name -> awecloud.signaling.STCPStatus
	11, // 2: awecloud.signaling.GetTCPServicesResponse.services:type_name -> awecloud.signaling.TCPServiceInfo
	1,  // 3: awecloud.signaling.AgentService.Register:input_type -> awecloud.signaling.RegisterRequest
	3,  // 4: awecloud.signaling.AgentService.Heartbeat:input_type -> awecloud.signaling.HeartbeatRequest
	6,  // 5: awecloud.signaling.AgentService.ReceiveCommands:input_type -> awecloud.signaling.CommandResponse
	7,  // 6: awecloud.signaling.AgentService.ReportStatus:input_type -> awecloud.signaling.StatusReport
	10, // 7: awecloud.signaling.AgentService.GetEnabledTCPServices:input_type -> awecloud.signaling.GetTCPServicesRequest
	2,  // 8: awecloud.signaling.AgentService.Register:output_type -> awecloud.signaling.RegisterResponse
	4,  // 9: awecloud.signaling.AgentService.Heartbeat:output_type -> awecloud.signaling.HeartbeatResponse
	5,  // 10: awecloud.signaling.AgentService.ReceiveCommands:output_type -> awecloud.signaling.Command
	9,  // 11: awecloud.signaling.AgentService.ReportStatus:output_type -> awecloud.signaling.StatusResponse
	12, // 12: awecloud.signaling.AgentService.GetEnabledTCPServices:output_type -> awecloud.signaling.GetTCPServicesResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_proto_agent_proto_init() }
func file_pkg_proto_agent_proto_init() {
	if File_pkg_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_agent_proto_rawDesc), len(file_pkg_proto_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_agent_proto_goTypes,
		DependencyIndexes: file_pkg_proto_agent_proto_depIdxs,
		EnumInfos:         file_pkg_proto_agent_proto_enumTypes,
		MessageInfos:      file_pkg_proto_agent_proto_msgTypes,
	}.Build()
	File_pkg_proto_agent_proto = out.File
	file_pkg_proto_agent_proto_goTypes = nil
	file_pkg_proto_agent_proto_depIdxs = nil
}
