// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.3
// source: pkg/proto/agent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_Register_FullMethodName              = "/awecloud.signaling.AgentService/Register"
	AgentService_Authenticate_FullMethodName          = "/awecloud.signaling.AgentService/Authenticate"
	AgentService_Heartbeat_FullMethodName             = "/awecloud.signaling.AgentService/Heartbeat"
	AgentService_ReportSupplyInventory_FullMethodName = "/awecloud.signaling.AgentService/ReportSupplyInventory"
	AgentService_GetRealtimeStatus_FullMethodName     = "/awecloud.signaling.AgentService/GetRealtimeStatus"
	AgentService_ReportProxyStatus_FullMethodName     = "/awecloud.signaling.AgentService/ReportProxyStatus"
	AgentService_ReportVisitorStatus_FullMethodName   = "/awecloud.signaling.AgentService/ReportVisitorStatus"
	AgentService_ReportNetworkChange_FullMethodName   = "/awecloud.signaling.AgentService/ReportNetworkChange"
	AgentService_SVCProxy_FullMethodName              = "/awecloud.signaling.AgentService/SVCProxy"
	AgentService_GetUserDeviceInfo_FullMethodName     = "/awecloud.signaling.AgentService/GetUserDeviceInfo"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService Agent 管理服务
type AgentServiceClient interface {
	// 注册 - Agent 首次连接时调用
	Register(ctx context.Context, in *AgentRegisterRequest, opts ...grpc.CallOption) (*AgentRegisterResponse, error)
	// 认证 - Agent 重连时调用
	Authenticate(ctx context.Context, in *AgentAuthenticateRequest, opts ...grpc.CallOption) (*AgentAuthenticateResponse, error)
	// 心跳 - 双向流，保持连接并同步状态
	Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentHeartbeatRequest, AgentHeartbeatResponse], error)
	// 上报完整供给清单；Agent 身份由既有 Deploy Token 验证。
	ReportSupplyInventory(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SupplyInventoryEnvelope, SupplyInventoryAck], error)
	// 获取实时状态 - Server 主动调用（用于 Web 详情页刷新）
	GetRealtimeStatus(ctx context.Context, in *GetRealtimeStatusRequest, opts ...grpc.CallOption) (*GetRealtimeStatusResponse, error)
	// 上报本地服务状态
	ReportProxyStatus(ctx context.Context, in *ReportProxyStatusRequest, opts ...grpc.CallOption) (*ReportProxyStatusResponse, error)
	// 上报远程服务状态
	ReportVisitorStatus(ctx context.Context, in *ReportVisitorStatusRequest, opts ...grpc.CallOption) (*ReportVisitorStatusResponse, error)
	// 上报网络变化
	ReportNetworkChange(ctx context.Context, in *ReportNetworkChangeRequest, opts ...grpc.CallOption) (*ReportNetworkChangeResponse, error)
	// SVCProxy - K8S Service 代理（双向流，Desktop → Agent → K8S ClusterIP）
	SVCProxy(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SVCProxyData, SVCProxyData], error)
	// 获取用户设备信息（用于 SSH 横幅显示）
	GetUserDeviceInfo(ctx context.Context, in *GetUserDeviceInfoRequest, opts ...grpc.CallOption) (*GetUserDeviceInfoResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Register(ctx context.Context, in *AgentRegisterRequest, opts ...grpc.CallOption) (*AgentRegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentRegisterResponse)
	err := c.cc.Invoke(ctx, AgentService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Authenticate(ctx context.Context, in *AgentAuthenticateRequest, opts ...grpc.CallOption) (*AgentAuthenticateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentAuthenticateResponse)
	err := c.cc.Invoke(ctx, AgentService_Authenticate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentHeartbeatRequest, AgentHeartbeatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_Heartbeat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentHeartbeatRequest, AgentHeartbeatResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_HeartbeatClient = grpc.BidiStreamingClient[AgentHeartbeatRequest, AgentHeartbeatResponse]

func (c *agentServiceClient) ReportSupplyInventory(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SupplyInventoryEnvelope, SupplyInventoryAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[1], AgentService_ReportSupplyInventory_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SupplyInventoryEnvelope, SupplyInventoryAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ReportSupplyInventoryClient = grpc.BidiStreamingClient[SupplyInventoryEnvelope, SupplyInventoryAck]

func (c *agentServiceClient) GetRealtimeStatus(ctx context.Context, in *GetRealtimeStatusRequest, opts ...grpc.CallOption) (*GetRealtimeStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRealtimeStatusResponse)
	err := c.cc.Invoke(ctx, AgentService_GetRealtimeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportProxyStatus(ctx context.Context, in *ReportProxyStatusRequest, opts ...grpc.CallOption) (*ReportProxyStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportProxyStatusResponse)
	err := c.cc.Invoke(ctx, AgentService_ReportProxyStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportVisitorStatus(ctx context.Context, in *ReportVisitorStatusRequest, opts ...grpc.CallOption) (*ReportVisitorStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportVisitorStatusResponse)
	err := c.cc.Invoke(ctx, AgentService_ReportVisitorStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportNetworkChange(ctx context.Context, in *ReportNetworkChangeRequest, opts ...grpc.CallOption) (*ReportNetworkChangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportNetworkChangeResponse)
	err := c.cc.Invoke(ctx, AgentService_ReportNetworkChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SVCProxy(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SVCProxyData, SVCProxyData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[2], AgentService_SVCProxy_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SVCProxyData, SVCProxyData]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_SVCProxyClient = grpc.BidiStreamingClient[SVCProxyData, SVCProxyData]

func (c *agentServiceClient) GetUserDeviceInfo(ctx context.Context, in *GetUserDeviceInfoRequest, opts ...grpc.CallOption) (*GetUserDeviceInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserDeviceInfoResponse)
	err := c.cc.Invoke(ctx, AgentService_GetUserDeviceInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService Agent 管理服务
type AgentServiceServer interface {
	// 注册 - Agent 首次连接时调用
	Register(context.Context, *AgentRegisterRequest) (*AgentRegisterResponse, error)
	// 认证 - Agent 重连时调用
	Authenticate(context.Context, *AgentAuthenticateRequest) (*AgentAuthenticateResponse, error)
	// 心跳 - 双向流，保持连接并同步状态
	Heartbeat(grpc.BidiStreamingServer[AgentHeartbeatRequest, AgentHeartbeatResponse]) error
	// 上报完整供给清单；Agent 身份由既有 Deploy Token 验证。
	ReportSupplyInventory(grpc.BidiStreamingServer[SupplyInventoryEnvelope, SupplyInventoryAck]) error
	// 获取实时状态 - Server 主动调用（用于 Web 详情页刷新）
	GetRealtimeStatus(context.Context, *GetRealtimeStatusRequest) (*GetRealtimeStatusResponse, error)
	// 上报本地服务状态
	ReportProxyStatus(context.Context, *ReportProxyStatusRequest) (*ReportProxyStatusResponse, error)
	// 上报远程服务状态
	ReportVisitorStatus(context.Context, *ReportVisitorStatusRequest) (*ReportVisitorStatusResponse, error)
	// 上报网络变化
	ReportNetworkChange(context.Context, *ReportNetworkChangeRequest) (*ReportNetworkChangeResponse, error)
	// SVCProxy - K8S Service 代理（双向流，Desktop → Agent → K8S ClusterIP）
	SVCProxy(grpc.BidiStreamingServer[SVCProxyData, SVCProxyData]) error
	// 获取用户设备信息（用于 SSH 横幅显示）
	GetUserDeviceInfo(context.Context, *GetUserDeviceInfoRequest) (*GetUserDeviceInfoResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Register(context.Context, *AgentRegisterRequest) (*AgentRegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAgentServiceServer) Authenticate(context.Context, *AgentAuthenticateRequest) (*AgentAuthenticateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedAgentServiceServer) Heartbeat(grpc.BidiStreamingServer[AgentHeartbeatRequest, AgentHeartbeatResponse]) error {
	return status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedAgentServiceServer) ReportSupplyInventory(grpc.BidiStreamingServer[SupplyInventoryEnvelope, SupplyInventoryAck]) error {
	return status.Error(codes.Unimplemented, "method ReportSupplyInventory not implemented")
}
func (UnimplementedAgentServiceServer) GetRealtimeStatus(context.Context, *GetRealtimeStatusRequest) (*GetRealtimeStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRealtimeStatus not implemented")
}
func (UnimplementedAgentServiceServer) ReportProxyStatus(context.Context, *ReportProxyStatusRequest) (*ReportProxyStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportProxyStatus not implemented")
}
func (UnimplementedAgentServiceServer) ReportVisitorStatus(context.Context, *ReportVisitorStatusRequest) (*ReportVisitorStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportVisitorStatus not implemented")
}
func (UnimplementedAgentServiceServer) ReportNetworkChange(context.Context, *ReportNetworkChangeRequest) (*ReportNetworkChangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportNetworkChange not implemented")
}
func (UnimplementedAgentServiceServer) SVCProxy(grpc.BidiStreamingServer[SVCProxyData, SVCProxyData]) error {
	return status.Error(codes.Unimplemented, "method SVCProxy not implemented")
}
func (UnimplementedAgentServiceServer) GetUserDeviceInfo(context.Context, *GetUserDeviceInfoRequest) (*GetUserDeviceInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserDeviceInfo not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Register(ctx, req.(*AgentRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentAuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Authenticate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Authenticate(ctx, req.(*AgentAuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Heartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).Heartbeat(&grpc.GenericServerStream[AgentHeartbeatRequest, AgentHeartbeatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_HeartbeatServer = grpc.BidiStreamingServer[AgentHeartbeatRequest, AgentHeartbeatResponse]

func _AgentService_ReportSupplyInventory_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).ReportSupplyInventory(&grpc.GenericServerStream[SupplyInventoryEnvelope, SupplyInventoryAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ReportSupplyInventoryServer = grpc.BidiStreamingServer[SupplyInventoryEnvelope, SupplyInventoryAck]

func _AgentService_GetRealtimeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRealtimeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetRealtimeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetRealtimeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetRealtimeStatus(ctx, req.(*GetRealtimeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportProxyStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportProxyStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportProxyStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportProxyStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportProxyStatus(ctx, req.(*ReportProxyStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportVisitorStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportVisitorStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportVisitorStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportVisitorStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportVisitorStatus(ctx, req.(*ReportVisitorStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportNetworkChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportNetworkChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportNetworkChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportNetworkChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportNetworkChange(ctx, req.(*ReportNetworkChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SVCProxy_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).SVCProxy(&grpc.GenericServerStream[SVCProxyData, SVCProxyData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_SVCProxyServer = grpc.BidiStreamingServer[SVCProxyData, SVCProxyData]

func _AgentService_GetUserDeviceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserDeviceInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetUserDeviceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetUserDeviceInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetUserDeviceInfo(ctx, req.(*GetUserDeviceInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "awecloud.signaling.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _AgentService_Register_Handler,
		},
		{
			MethodName: "Authenticate",
			Handler:    _AgentService_Authenticate_Handler,
		},
		{
			MethodName: "GetRealtimeStatus",
			Handler:    _AgentService_GetRealtimeStatus_Handler,
		},
		{
			MethodName: "ReportProxyStatus",
			Handler:    _AgentService_ReportProxyStatus_Handler,
		},
		{
			MethodName: "ReportVisitorStatus",
			Handler:    _AgentService_ReportVisitorStatus_Handler,
		},
		{
			MethodName: "ReportNetworkChange",
			Handler:    _AgentService_ReportNetworkChange_Handler,
		},
		{
			MethodName: "GetUserDeviceInfo",
			Handler:    _AgentService_GetUserDeviceInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Heartbeat",
			Handler:       _AgentService_Heartbeat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ReportSupplyInventory",
			Handler:       _AgentService_ReportSupplyInventory_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SVCProxy",
			Handler:       _AgentService_SVCProxy_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/proto/agent.proto",
}
