// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: pkg/proto/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SystemInfo 系统信息
type SystemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`                                // 操作系统：linux / windows / darwin
	OsVersion     string                 `protobuf:"bytes,2,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"` // 系统版本
	Arch          string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`                            // CPU 架构：amd64 / arm64
	Hostname      string                 `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`                    // 主机名
	Cpu           string                 `protobuf:"bytes,5,opt,name=cpu,proto3" json:"cpu,omitempty"`                              // CPU 型号
	CpuCores      int32                  `protobuf:"varint,6,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`   // CPU 核心数
	MemoryGb      int32                  `protobuf:"varint,7,opt,name=memory_gb,json=memoryGb,proto3" json:"memory_gb,omitempty"`   // 内存大小（GB）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_pkg_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *SystemInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SystemInfo) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *SystemInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *SystemInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SystemInfo) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *SystemInfo) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *SystemInfo) GetMemoryGb() int32 {
	if x != nil {
		return x.MemoryGb
	}
	return 0
}

// NetworkInterface 网络接口信息
type NetworkInterface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`       // 网卡名称（如 eth0, ens192）
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`           // IP 地址
	Mask          string                 `protobuf:"bytes,3,opt,name=mask,proto3" json:"mask,omitempty"`       // 子网掩码
	Gateway       string                 `protobuf:"bytes,4,opt,name=gateway,proto3" json:"gateway,omitempty"` // 网关地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInterface) Reset() {
	*x = NetworkInterface{}
	mi := &file_pkg_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInterface) ProtoMessage() {}

func (x *NetworkInterface) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInterface.ProtoReflect.Descriptor instead.
func (*NetworkInterface) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *NetworkInterface) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkInterface) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *NetworkInterface) GetMask() string {
	if x != nil {
		return x.Mask
	}
	return ""
}

func (x *NetworkInterface) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

// AgentRegisterRequest Agent 注册请求
type AgentRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                               // Agent 名称
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`                           // 认证密钥
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                         // Agent 版本号
	SystemInfo    *SystemInfo            `protobuf:"bytes,4,opt,name=system_info,json=systemInfo,proto3" json:"system_info,omitempty"` // 系统信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRegisterRequest) Reset() {
	*x = AgentRegisterRequest{}
	mi := &file_pkg_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRegisterRequest) ProtoMessage() {}

func (x *AgentRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRegisterRequest.ProtoReflect.Descriptor instead.
func (*AgentRegisterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AgentRegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentRegisterRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *AgentRegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentRegisterRequest) GetSystemInfo() *SystemInfo {
	if x != nil {
		return x.SystemInfo
	}
	return nil
}

// AgentRegisterResponse Agent 注册响应
type AgentRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                     // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                      // 响应消息
	AgentId       uint64                 `protobuf:"varint,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`      // Agent ID（Headscale User ID）
	AuthKey       string                 `protobuf:"bytes,4,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"`       // Tailscale PreAuthKey，用于隧道连接
	ServerUrl     string                 `protobuf:"bytes,5,opt,name=server_url,json=serverUrl,proto3" json:"server_url,omitempty"` // Headscale 服务器地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRegisterResponse) Reset() {
	*x = AgentRegisterResponse{}
	mi := &file_pkg_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRegisterResponse) ProtoMessage() {}

func (x *AgentRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRegisterResponse.ProtoReflect.Descriptor instead.
func (*AgentRegisterResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AgentRegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AgentRegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AgentRegisterResponse) GetAgentId() uint64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *AgentRegisterResponse) GetAuthKey() string {
	if x != nil {
		return x.AuthKey
	}
	return ""
}

func (x *AgentRegisterResponse) GetServerUrl() string {
	if x != nil {
		return x.ServerUrl
	}
	return ""
}

// AgentAuthenticateRequest Agent 认证请求
type AgentAuthenticateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       uint64                 `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`         // Agent ID
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`                           // 认证密钥
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                         // Agent 版本号
	SystemInfo    *SystemInfo            `protobuf:"bytes,4,opt,name=system_info,json=systemInfo,proto3" json:"system_info,omitempty"` // 系统信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentAuthenticateRequest) Reset() {
	*x = AgentAuthenticateRequest{}
	mi := &file_pkg_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentAuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentAuthenticateRequest) ProtoMessage() {}

func (x *AgentAuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentAuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AgentAuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *AgentAuthenticateRequest) GetAgentId() uint64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *AgentAuthenticateRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *AgentAuthenticateRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentAuthenticateRequest) GetSystemInfo() *SystemInfo {
	if x != nil {
		return x.SystemInfo
	}
	return nil
}

// AgentAuthenticateResponse Agent 认证响应
type AgentAuthenticateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                     // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                      // 响应消息
	AuthKey       string                 `protobuf:"bytes,3,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"`       // Tailscale PreAuthKey（如需重新连接）
	ServerUrl     string                 `protobuf:"bytes,4,opt,name=server_url,json=serverUrl,proto3" json:"server_url,omitempty"` // Headscale 服务器地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentAuthenticateResponse) Reset() {
	*x = AgentAuthenticateResponse{}
	mi := &file_pkg_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentAuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentAuthenticateResponse) ProtoMessage() {}

func (x *AgentAuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentAuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AgentAuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *AgentAuthenticateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AgentAuthenticateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AgentAuthenticateResponse) GetAuthKey() string {
	if x != nil {
		return x.AuthKey
	}
	return ""
}

func (x *AgentAuthenticateResponse) GetServerUrl() string {
	if x != nil {
		return x.ServerUrl
	}
	return ""
}

// ServiceStatus 端口映射服务状态
type ServiceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"` // 服务 ID
	Running       bool                   `protobuf:"varint,2,opt,name=running,proto3" json:"running,omitempty"`                     // 是否运行中
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                          // 错误信息（如有）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceStatus) Reset() {
	*x = ServiceStatus{}
	mi := &file_pkg_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStatus) ProtoMessage() {}

func (x *ServiceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStatus.ProtoReflect.Descriptor instead.
func (*ServiceStatus) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ServiceStatus) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ServiceStatus) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *ServiceStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ForwardStatus 端口访问服务状态
type ForwardStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ForwardId     string                 `protobuf:"bytes,1,opt,name=forward_id,json=forwardId,proto3" json:"forward_id,omitempty"` // 端口访问 ID
	Running       bool                   `protobuf:"varint,2,opt,name=running,proto3" json:"running,omitempty"`                     // 是否运行中
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                          // 错误信息（如有）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardStatus) Reset() {
	*x = ForwardStatus{}
	mi := &file_pkg_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardStatus) ProtoMessage() {}

func (x *ForwardStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardStatus.ProtoReflect.Descriptor instead.
func (*ForwardStatus) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ForwardStatus) GetForwardId() string {
	if x != nil {
		return x.ForwardId
	}
	return ""
}

func (x *ForwardStatus) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *ForwardStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// AgentHeartbeatRequest Agent 心跳请求
type AgentHeartbeatRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentId         uint64                 `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                         // Agent ID
	TunnelIp        string                 `protobuf:"bytes,2,opt,name=tunnel_ip,json=tunnelIp,proto3" json:"tunnel_ip,omitempty"`                       // 隧道 IP
	TunnelConnected bool                   `protobuf:"varint,3,opt,name=tunnel_connected,json=tunnelConnected,proto3" json:"tunnel_connected,omitempty"` // 隧道连接状态
	ServiceStatus   []*ServiceStatus       `protobuf:"bytes,4,rep,name=service_status,json=serviceStatus,proto3" json:"service_status,omitempty"`        // 端口映射服务状态列表
	ForwardStatus   []*ForwardStatus       `protobuf:"bytes,5,rep,name=forward_status,json=forwardStatus,proto3" json:"forward_status,omitempty"`        // 端口访问服务状态列表
	// 网络信息（首次心跳或变更时上报）
	Hostname string              `protobuf:"bytes,6,opt,name=hostname,proto3" json:"hostname,omitempty"` // 主机名
	Runtime  string              `protobuf:"bytes,7,opt,name=runtime,proto3" json:"runtime,omitempty"`   // 运行环境：docker / kubernetes / physical
	Networks []*NetworkInterface `protobuf:"bytes,8,rep,name=networks,proto3" json:"networks,omitempty"` // 网络接口列表
	// ZTNA 域名注册（首次心跳或变更时上报）
	DomainRegistrations []*DomainRegistration `protobuf:"bytes,9,rep,name=domain_registrations,json=domainRegistrations,proto3" json:"domain_registrations,omitempty"` // 域名注册列表
	// K8S Service 发现数据（Agent 上报）
	DiscoveredServices []*DiscoveredK8SService `protobuf:"bytes,10,rep,name=discovered_services,json=discoveredServices,proto3" json:"discovered_services,omitempty"` // 发现的 K8S Service 列表
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AgentHeartbeatRequest) Reset() {
	*x = AgentHeartbeatRequest{}
	mi := &file_pkg_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHeartbeatRequest) ProtoMessage() {}

func (x *AgentHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*AgentHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *AgentHeartbeatRequest) GetAgentId() uint64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *AgentHeartbeatRequest) GetTunnelIp() string {
	if x != nil {
		return x.TunnelIp
	}
	return ""
}

func (x *AgentHeartbeatRequest) GetTunnelConnected() bool {
	if x != nil {
		return x.TunnelConnected
	}
	return false
}

func (x *AgentHeartbeatRequest) GetServiceStatus() []*ServiceStatus {
	if x != nil {
		return x.ServiceStatus
	}
	return nil
}

func (x *AgentHeartbeatRequest) GetForwardStatus() []*ForwardStatus {
	if x != nil {
		return x.ForwardStatus
	}
	return nil
}

func (x *AgentHeartbeatRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentHeartbeatRequest) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *AgentHeartbeatRequest) GetNetworks() []*NetworkInterface {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *AgentHeartbeatRequest) GetDomainRegistrations() []*DomainRegistration {
	if x != nil {
		return x.DomainRegistrations
	}
	return nil
}

func (x *AgentHeartbeatRequest) GetDiscoveredServices() []*DiscoveredK8SService {
	if x != nil {
		return x.DiscoveredServices
	}
	return nil
}

// DiscoveredK8SService Agent 发现的 K8S Service（心跳上报）
type DiscoveredK8SService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`                                                                     // 命名空间
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`                                              // Service 名称
	ClusterIp     string                 `protobuf:"bytes,3,opt,name=cluster_ip,json=clusterIp,proto3" json:"cluster_ip,omitempty"`                                                    // ClusterIP
	Ports         []*ServicePort         `protobuf:"bytes,4,rep,name=ports,proto3" json:"ports,omitempty"`                                                                             // 端口列表
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 标签
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveredK8SService) Reset() {
	*x = DiscoveredK8SService{}
	mi := &file_pkg_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveredK8SService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveredK8SService) ProtoMessage() {}

func (x *DiscoveredK8SService) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveredK8SService.ProtoReflect.Descriptor instead.
func (*DiscoveredK8SService) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *DiscoveredK8SService) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DiscoveredK8SService) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *DiscoveredK8SService) GetClusterIp() string {
	if x != nil {
		return x.ClusterIp
	}
	return ""
}

func (x *DiscoveredK8SService) GetPorts() []*ServicePort {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *DiscoveredK8SService) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// ServicePort K8S Service 端口
type ServicePort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`         // 端口名称
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`        // 端口号
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"` // 协议（TCP/UDP）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServicePort) Reset() {
	*x = ServicePort{}
	mi := &file_pkg_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServicePort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicePort) ProtoMessage() {}

func (x *ServicePort) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicePort.ProtoReflect.Descriptor instead.
func (*ServicePort) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ServicePort) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServicePort) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServicePort) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

// DomainRegistration 域名注册信息（Agent 心跳上报）
type DomainRegistration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`                              // 完整域名（如 beagle-242.beijing.beagle）
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                                  // 能力类型：ssh / k8sapi / k8ssvc
	TargetIp      string                 `protobuf:"bytes,3,opt,name=target_ip,json=targetIp,proto3" json:"target_ip,omitempty"`          // 目标 IP（Node 的 Tailscale IP 或 ClusterIP）
	TargetPort    int32                  `protobuf:"varint,4,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`   // 目标端口
	Namespace     string                 `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`                        // K8S 命名空间（k8ssvc 类型时）
	ServiceName   string                 `protobuf:"bytes,6,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // K8S Service 名称（k8ssvc 类型时）
	EndpointId    string                 `protobuf:"bytes,7,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`    // 关联的 Endpoint ID（Endpoint 类型时）
	NodeId        uint64                 `protobuf:"varint,8,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`               // 关联的 Node ID（Node 注册时）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainRegistration) Reset() {
	*x = DomainRegistration{}
	mi := &file_pkg_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainRegistration) ProtoMessage() {}

func (x *DomainRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainRegistration.ProtoReflect.Descriptor instead.
func (*DomainRegistration) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *DomainRegistration) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DomainRegistration) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DomainRegistration) GetTargetIp() string {
	if x != nil {
		return x.TargetIp
	}
	return ""
}

func (x *DomainRegistration) GetTargetPort() int32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *DomainRegistration) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DomainRegistration) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *DomainRegistration) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *DomainRegistration) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

// ServiceConfig 端口映射配置
type ServiceConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                   // 服务 ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                               // 服务名称
	SourceAddr    string                 `protobuf:"bytes,3,opt,name=source_addr,json=sourceAddr,proto3" json:"source_addr,omitempty"` // 源地址（VPN IP:端口，如 100.64.0.1:80）
	TargetAddr    string                 `protobuf:"bytes,4,opt,name=target_addr,json=targetAddr,proto3" json:"target_addr,omitempty"` // 目标地址（局域网地址，如 192.168.1.10:80）
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`                        // 是否启用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceConfig) Reset() {
	*x = ServiceConfig{}
	mi := &file_pkg_proto_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceConfig) ProtoMessage() {}

func (x *ServiceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceConfig.ProtoReflect.Descriptor instead.
func (*ServiceConfig) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ServiceConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceConfig) GetSourceAddr() string {
	if x != nil {
		return x.SourceAddr
	}
	return ""
}

func (x *ServiceConfig) GetTargetAddr() string {
	if x != nil {
		return x.TargetAddr
	}
	return ""
}

func (x *ServiceConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// ForwardConfig 端口访问配置
type ForwardConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                      // 端口访问 ID
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`       // 关联的目标服务 ID
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // 关联的目标服务名称
	SourceAddr    string                 `protobuf:"bytes,4,opt,name=source_addr,json=sourceAddr,proto3" json:"source_addr,omitempty"`    // 源地址（局域网 IP:端口，如 192.168.1.100:13306）
	TargetAddr    string                 `protobuf:"bytes,5,opt,name=target_addr,json=targetAddr,proto3" json:"target_addr,omitempty"`    // 目标地址（VPN 地址，如 100.64.0.1:3306）
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`                           // 是否启用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardConfig) Reset() {
	*x = ForwardConfig{}
	mi := &file_pkg_proto_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardConfig) ProtoMessage() {}

func (x *ForwardConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardConfig.ProtoReflect.Descriptor instead.
func (*ForwardConfig) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ForwardConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ForwardConfig) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ForwardConfig) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ForwardConfig) GetSourceAddr() string {
	if x != nil {
		return x.SourceAddr
	}
	return ""
}

func (x *ForwardConfig) GetTargetAddr() string {
	if x != nil {
		return x.TargetAddr
	}
	return ""
}

func (x *ForwardConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// AgentHeartbeatResponse Agent 心跳响应
type AgentHeartbeatResponse struct {
	state                  protoimpl.MessageState  `protogen:"open.v1"`
	ConfigVersion          int64                   `protobuf:"varint,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`                              // 配置版本号
	Services               []*ServiceConfig        `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`                                                              // 端口映射配置（如有变更）
	Forwards               []*ForwardConfig        `protobuf:"bytes,3,rep,name=forwards,proto3" json:"forwards,omitempty"`                                                              // 端口访问配置（如有变更）
	DomainSuffix           string                  `protobuf:"bytes,4,opt,name=domain_suffix,json=domainSuffix,proto3" json:"domain_suffix,omitempty"`                                  // 域名后缀（如 .beagle），由 Server 下发
	K8SPermissions         []*K8SPermission        `protobuf:"bytes,5,rep,name=k8s_permissions,json=k8sPermissions,proto3" json:"k8s_permissions,omitempty"`                            // K8S API 授权列表
	K8SServicePermissions  []*K8SServicePermission `protobuf:"bytes,6,rep,name=k8s_service_permissions,json=k8sServicePermissions,proto3" json:"k8s_service_permissions,omitempty"`     // K8S Service 授权列表
	RequestImmediateReport bool                    `protobuf:"varint,7,opt,name=request_immediate_report,json=requestImmediateReport,proto3" json:"request_immediate_report,omitempty"` // Server 请求 Agent 立即上报一次心跳数据
	CapabilityConfig       *AgentCapabilityConfig  `protobuf:"bytes,8,opt,name=capability_config,json=capabilityConfig,proto3" json:"capability_config,omitempty"`                      // Agent 能力配置（Server 远程控制）
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AgentHeartbeatResponse) Reset() {
	*x = AgentHeartbeatResponse{}
	mi := &file_pkg_proto_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHeartbeatResponse) ProtoMessage() {}

func (x *AgentHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*AgentHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{14}
}

func (x *AgentHeartbeatResponse) GetConfigVersion() int64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *AgentHeartbeatResponse) GetServices() []*ServiceConfig {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *AgentHeartbeatResponse) GetForwards() []*ForwardConfig {
	if x != nil {
		return x.Forwards
	}
	return nil
}

func (x *AgentHeartbeatResponse) GetDomainSuffix() string {
	if x != nil {
		return x.DomainSuffix
	}
	return ""
}

func (x *AgentHeartbeatResponse) GetK8SPermissions() []*K8SPermission {
	if x != nil {
		return x.K8SPermissions
	}
	return nil
}

func (x *AgentHeartbeatResponse) GetK8SServicePermissions() []*K8SServicePermission {
	if x != nil {
		return x.K8SServicePermissions
	}
	return nil
}

func (x *AgentHeartbeatResponse) GetRequestImmediateReport() bool {
	if x != nil {
		return x.RequestImmediateReport
	}
	return false
}

func (x *AgentHeartbeatResponse) GetCapabilityConfig() *AgentCapabilityConfig {
	if x != nil {
		return x.CapabilityConfig
	}
	return nil
}

// AgentCapabilityConfig Agent 能力配置（Server 远程控制）
// 通过 xxx_set 标志位区分"Server 设置为 false/0"和"Server 未设置"
type AgentCapabilityConfig struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SshEnabled           bool                   `protobuf:"varint,1,opt,name=ssh_enabled,json=sshEnabled,proto3" json:"ssh_enabled,omitempty"`                                      // SSH 开关
	SshEnabledSet        bool                   `protobuf:"varint,2,opt,name=ssh_enabled_set,json=sshEnabledSet,proto3" json:"ssh_enabled_set,omitempty"`                           // SSH 开关是否由 Server 设置（始终为 true）
	K8SEnabled           bool                   `protobuf:"varint,3,opt,name=k8s_enabled,json=k8sEnabled,proto3" json:"k8s_enabled,omitempty"`                                      // K8S API 开关
	K8SEnabledSet        bool                   `protobuf:"varint,4,opt,name=k8s_enabled_set,json=k8sEnabledSet,proto3" json:"k8s_enabled_set,omitempty"`                           // K8S API 开关是否由 Server 设置
	K8SListenPort        int32                  `protobuf:"varint,5,opt,name=k8s_listen_port,json=k8sListenPort,proto3" json:"k8s_listen_port,omitempty"`                           // K8S API 监听端口
	K8SListenPortSet     bool                   `protobuf:"varint,6,opt,name=k8s_listen_port_set,json=k8sListenPortSet,proto3" json:"k8s_listen_port_set,omitempty"`                // K8S API 监听端口是否由 Server 设置
	K8SApiServer         string                 `protobuf:"bytes,7,opt,name=k8s_api_server,json=k8sApiServer,proto3" json:"k8s_api_server,omitempty"`                               // K8S API Server 地址
	K8SApiServerSet      bool                   `protobuf:"varint,8,opt,name=k8s_api_server_set,json=k8sApiServerSet,proto3" json:"k8s_api_server_set,omitempty"`                   // K8S API Server 地址是否由 Server 设置
	SvcEnabled           bool                   `protobuf:"varint,9,opt,name=svc_enabled,json=svcEnabled,proto3" json:"svc_enabled,omitempty"`                                      // K8S Service 开关
	SvcEnabledSet        bool                   `protobuf:"varint,10,opt,name=svc_enabled_set,json=svcEnabledSet,proto3" json:"svc_enabled_set,omitempty"`                          // K8S Service 开关是否由 Server 设置
	SvcLabelSelector     string                 `protobuf:"bytes,11,opt,name=svc_label_selector,json=svcLabelSelector,proto3" json:"svc_label_selector,omitempty"`                  // 标签选择器
	SvcLabelSelectorSet  bool                   `protobuf:"varint,12,opt,name=svc_label_selector_set,json=svcLabelSelectorSet,proto3" json:"svc_label_selector_set,omitempty"`      // 标签选择器是否由 Server 设置
	SvcNamespaces        string                 `protobuf:"bytes,13,opt,name=svc_namespaces,json=svcNamespaces,proto3" json:"svc_namespaces,omitempty"`                             // 命名空间列表（逗号分隔）
	SvcNamespacesSet     bool                   `protobuf:"varint,14,opt,name=svc_namespaces_set,json=svcNamespacesSet,proto3" json:"svc_namespaces_set,omitempty"`                 // 命名空间列表是否由 Server 设置
	SvcListenPortBase    int32                  `protobuf:"varint,15,opt,name=svc_listen_port_base,json=svcListenPortBase,proto3" json:"svc_listen_port_base,omitempty"`            // gRPC 监听端口
	SvcListenPortBaseSet bool                   `protobuf:"varint,16,opt,name=svc_listen_port_base_set,json=svcListenPortBaseSet,proto3" json:"svc_listen_port_base_set,omitempty"` // gRPC 监听端口是否由 Server 设置
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AgentCapabilityConfig) Reset() {
	*x = AgentCapabilityConfig{}
	mi := &file_pkg_proto_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCapabilityConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCapabilityConfig) ProtoMessage() {}

func (x *AgentCapabilityConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCapabilityConfig.ProtoReflect.Descriptor instead.
func (*AgentCapabilityConfig) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{15}
}

func (x *AgentCapabilityConfig) GetSshEnabled() bool {
	if x != nil {
		return x.SshEnabled
	}
	return false
}

func (x *AgentCapabilityConfig) GetSshEnabledSet() bool {
	if x != nil {
		return x.SshEnabledSet
	}
	return false
}

func (x *AgentCapabilityConfig) GetK8SEnabled() bool {
	if x != nil {
		return x.K8SEnabled
	}
	return false
}

func (x *AgentCapabilityConfig) GetK8SEnabledSet() bool {
	if x != nil {
		return x.K8SEnabledSet
	}
	return false
}

func (x *AgentCapabilityConfig) GetK8SListenPort() int32 {
	if x != nil {
		return x.K8SListenPort
	}
	return 0
}

func (x *AgentCapabilityConfig) GetK8SListenPortSet() bool {
	if x != nil {
		return x.K8SListenPortSet
	}
	return false
}

func (x *AgentCapabilityConfig) GetK8SApiServer() string {
	if x != nil {
		return x.K8SApiServer
	}
	return ""
}

func (x *AgentCapabilityConfig) GetK8SApiServerSet() bool {
	if x != nil {
		return x.K8SApiServerSet
	}
	return false
}

func (x *AgentCapabilityConfig) GetSvcEnabled() bool {
	if x != nil {
		return x.SvcEnabled
	}
	return false
}

func (x *AgentCapabilityConfig) GetSvcEnabledSet() bool {
	if x != nil {
		return x.SvcEnabledSet
	}
	return false
}

func (x *AgentCapabilityConfig) GetSvcLabelSelector() string {
	if x != nil {
		return x.SvcLabelSelector
	}
	return ""
}

func (x *AgentCapabilityConfig) GetSvcLabelSelectorSet() bool {
	if x != nil {
		return x.SvcLabelSelectorSet
	}
	return false
}

func (x *AgentCapabilityConfig) GetSvcNamespaces() string {
	if x != nil {
		return x.SvcNamespaces
	}
	return ""
}

func (x *AgentCapabilityConfig) GetSvcNamespacesSet() bool {
	if x != nil {
		return x.SvcNamespacesSet
	}
	return false
}

func (x *AgentCapabilityConfig) GetSvcListenPortBase() int32 {
	if x != nil {
		return x.SvcListenPortBase
	}
	return 0
}

func (x *AgentCapabilityConfig) GetSvcListenPortBaseSet() bool {
	if x != nil {
		return x.SvcListenPortBaseSet
	}
	return false
}

// K8SPermission K8S API 授权信息（心跳响应下发给 Agent）
type K8SPermission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`         // 被授权用户 ID
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`    // 被授权用户名
	K8SGroups     []string               `protobuf:"bytes,3,rep,name=k8s_groups,json=k8sGroups,proto3" json:"k8s_groups,omitempty"` // K8S Impersonation 分组
	Namespaces    []string               `protobuf:"bytes,4,rep,name=namespaces,proto3" json:"namespaces,omitempty"`                // 允许的命名空间（空表示全部）
	IsGroup       bool                   `protobuf:"varint,5,opt,name=is_group,json=isGroup,proto3" json:"is_group,omitempty"`      // 是否来自分组授权
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *K8SPermission) Reset() {
	*x = K8SPermission{}
	mi := &file_pkg_proto_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SPermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SPermission) ProtoMessage() {}

func (x *K8SPermission) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SPermission.ProtoReflect.Descriptor instead.
func (*K8SPermission) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{16}
}

func (x *K8SPermission) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *K8SPermission) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *K8SPermission) GetK8SGroups() []string {
	if x != nil {
		return x.K8SGroups
	}
	return nil
}

func (x *K8SPermission) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *K8SPermission) GetIsGroup() bool {
	if x != nil {
		return x.IsGroup
	}
	return false
}

// K8SServicePermission K8S Service 授权信息（心跳响应下发给 Agent）
type K8SServicePermission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                  // 被授权用户 ID
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`             // 被授权用户名
	Namespaces    []string               `protobuf:"bytes,3,rep,name=namespaces,proto3" json:"namespaces,omitempty"`                         // 允许的命名空间（空表示全部）
	ServiceNames  []string               `protobuf:"bytes,4,rep,name=service_names,json=serviceNames,proto3" json:"service_names,omitempty"` // 允许的 Service 名称（空表示全部）
	IsGroup       bool                   `protobuf:"varint,5,opt,name=is_group,json=isGroup,proto3" json:"is_group,omitempty"`               // 是否来自分组授权
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *K8SServicePermission) Reset() {
	*x = K8SServicePermission{}
	mi := &file_pkg_proto_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SServicePermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SServicePermission) ProtoMessage() {}

func (x *K8SServicePermission) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SServicePermission.ProtoReflect.Descriptor instead.
func (*K8SServicePermission) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{17}
}

func (x *K8SServicePermission) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *K8SServicePermission) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *K8SServicePermission) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *K8SServicePermission) GetServiceNames() []string {
	if x != nil {
		return x.ServiceNames
	}
	return nil
}

func (x *K8SServicePermission) GetIsGroup() bool {
	if x != nil {
		return x.IsGroup
	}
	return false
}

// GetRealtimeStatusRequest 获取实时状态请求
type GetRealtimeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       uint64                 `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // Agent ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRealtimeStatusRequest) Reset() {
	*x = GetRealtimeStatusRequest{}
	mi := &file_pkg_proto_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRealtimeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRealtimeStatusRequest) ProtoMessage() {}

func (x *GetRealtimeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRealtimeStatusRequest.ProtoReflect.Descriptor instead.
func (*GetRealtimeStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{18}
}

func (x *GetRealtimeStatusRequest) GetAgentId() uint64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

// GetRealtimeStatusResponse 获取实时状态响应
type GetRealtimeStatusResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Hostname            string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`                                                     // 主机名
	Runtime             string                 `protobuf:"bytes,2,opt,name=runtime,proto3" json:"runtime,omitempty"`                                                       // 运行环境：docker / k8s / vm / physical
	Networks            []*NetworkInterface    `protobuf:"bytes,3,rep,name=networks,proto3" json:"networks,omitempty"`                                                     // 网络接口列表
	TunnelIp            string                 `protobuf:"bytes,4,opt,name=tunnel_ip,json=tunnelIp,proto3" json:"tunnel_ip,omitempty"`                                     // 隧道 IP
	TunnelConnected     bool                   `protobuf:"varint,5,opt,name=tunnel_connected,json=tunnelConnected,proto3" json:"tunnel_connected,omitempty"`               // 隧道连接状态
	TunnelConnectedTime int64                  `protobuf:"varint,6,opt,name=tunnel_connected_time,json=tunnelConnectedTime,proto3" json:"tunnel_connected_time,omitempty"` // 隧道连接时间（Unix 时间戳）
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetRealtimeStatusResponse) Reset() {
	*x = GetRealtimeStatusResponse{}
	mi := &file_pkg_proto_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRealtimeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRealtimeStatusResponse) ProtoMessage() {}

func (x *GetRealtimeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRealtimeStatusResponse.ProtoReflect.Descriptor instead.
func (*GetRealtimeStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{19}
}

func (x *GetRealtimeStatusResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *GetRealtimeStatusResponse) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *GetRealtimeStatusResponse) GetNetworks() []*NetworkInterface {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *GetRealtimeStatusResponse) GetTunnelIp() string {
	if x != nil {
		return x.TunnelIp
	}
	return ""
}

func (x *GetRealtimeStatusResponse) GetTunnelConnected() bool {
	if x != nil {
		return x.TunnelConnected
	}
	return false
}

func (x *GetRealtimeStatusResponse) GetTunnelConnectedTime() int64 {
	if x != nil {
		return x.TunnelConnectedTime
	}
	return 0
}

// ProxyStatus 本地服务状态
type ProxyStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"` // 服务 ID
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                        // 状态：running/disabled/error/pending
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"` // 错误代码
	ErrorMsg      string                 `protobuf:"bytes,4,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`    // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyStatus) Reset() {
	*x = ProxyStatus{}
	mi := &file_pkg_proto_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyStatus) ProtoMessage() {}

func (x *ProxyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyStatus.ProtoReflect.Descriptor instead.
func (*ProxyStatus) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{20}
}

func (x *ProxyStatus) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ProxyStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProxyStatus) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ProxyStatus) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

// ReportProxyStatusRequest 上报本地服务状态请求
type ReportProxyStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       uint64                 `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // Agent ID
	Statuses      []*ProxyStatus         `protobuf:"bytes,2,rep,name=statuses,proto3" json:"statuses,omitempty"`               // 状态列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportProxyStatusRequest) Reset() {
	*x = ReportProxyStatusRequest{}
	mi := &file_pkg_proto_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportProxyStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportProxyStatusRequest) ProtoMessage() {}

func (x *ReportProxyStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportProxyStatusRequest.ProtoReflect.Descriptor instead.
func (*ReportProxyStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{21}
}

func (x *ReportProxyStatusRequest) GetAgentId() uint64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *ReportProxyStatusRequest) GetStatuses() []*ProxyStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

// ReportProxyStatusResponse 上报本地服务状态响应
type ReportProxyStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportProxyStatusResponse) Reset() {
	*x = ReportProxyStatusResponse{}
	mi := &file_pkg_proto_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportProxyStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportProxyStatusResponse) ProtoMessage() {}

func (x *ReportProxyStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportProxyStatusResponse.ProtoReflect.Descriptor instead.
func (*ReportProxyStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{22}
}

func (x *ReportProxyStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportProxyStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// VisitorStatus 远程服务状态
type VisitorStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ForwardId      string                 `protobuf:"bytes,1,opt,name=forward_id,json=forwardId,proto3" json:"forward_id,omitempty"`                // 远程服务 ID
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                       // 状态：running/disabled/error/pending
	ConfiguredAddr string                 `protobuf:"bytes,3,opt,name=configured_addr,json=configuredAddr,proto3" json:"configured_addr,omitempty"` // 配置的源地址
	ActualAddr     string                 `protobuf:"bytes,4,opt,name=actual_addr,json=actualAddr,proto3" json:"actual_addr,omitempty"`             // 实际使用的源地址
	IpChanged      bool                   `protobuf:"varint,5,opt,name=ip_changed,json=ipChanged,proto3" json:"ip_changed,omitempty"`               // IP 是否变化
	ChangeReason   string                 `protobuf:"bytes,6,opt,name=change_reason,json=changeReason,proto3" json:"change_reason,omitempty"`       // 变化原因：DHCP_IP_CHANGE / NETWORK_INTERFACE_LOST
	ErrorCode      string                 `protobuf:"bytes,7,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`                // 错误代码
	ErrorMsg       string                 `protobuf:"bytes,8,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`                   // 错误信息
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VisitorStatus) Reset() {
	*x = VisitorStatus{}
	mi := &file_pkg_proto_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitorStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitorStatus) ProtoMessage() {}

func (x *VisitorStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitorStatus.ProtoReflect.Descriptor instead.
func (*VisitorStatus) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{23}
}

func (x *VisitorStatus) GetForwardId() string {
	if x != nil {
		return x.ForwardId
	}
	return ""
}

func (x *VisitorStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VisitorStatus) GetConfiguredAddr() string {
	if x != nil {
		return x.ConfiguredAddr
	}
	return ""
}

func (x *VisitorStatus) GetActualAddr() string {
	if x != nil {
		return x.ActualAddr
	}
	return ""
}

func (x *VisitorStatus) GetIpChanged() bool {
	if x != nil {
		return x.IpChanged
	}
	return false
}

func (x *VisitorStatus) GetChangeReason() string {
	if x != nil {
		return x.ChangeReason
	}
	return ""
}

func (x *VisitorStatus) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *VisitorStatus) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

// ReportVisitorStatusRequest 上报远程服务状态请求
type ReportVisitorStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       uint64                 `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // Agent ID
	Statuses      []*VisitorStatus       `protobuf:"bytes,2,rep,name=statuses,proto3" json:"statuses,omitempty"`               // 状态列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportVisitorStatusRequest) Reset() {
	*x = ReportVisitorStatusRequest{}
	mi := &file_pkg_proto_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportVisitorStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportVisitorStatusRequest) ProtoMessage() {}

func (x *ReportVisitorStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportVisitorStatusRequest.ProtoReflect.Descriptor instead.
func (*ReportVisitorStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{24}
}

func (x *ReportVisitorStatusRequest) GetAgentId() uint64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *ReportVisitorStatusRequest) GetStatuses() []*VisitorStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

// ReportVisitorStatusResponse 上报远程服务状态响应
type ReportVisitorStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportVisitorStatusResponse) Reset() {
	*x = ReportVisitorStatusResponse{}
	mi := &file_pkg_proto_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportVisitorStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportVisitorStatusResponse) ProtoMessage() {}

func (x *ReportVisitorStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportVisitorStatusResponse.ProtoReflect.Descriptor instead.
func (*ReportVisitorStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{25}
}

func (x *ReportVisitorStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportVisitorStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ReportNetworkChangeRequest 上报网络变化请求
type ReportNetworkChangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       uint64                 `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // Agent ID
	Networks      []*NetworkInterface    `protobuf:"bytes,2,rep,name=networks,proto3" json:"networks,omitempty"`               // 新的网络接口列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportNetworkChangeRequest) Reset() {
	*x = ReportNetworkChangeRequest{}
	mi := &file_pkg_proto_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportNetworkChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportNetworkChangeRequest) ProtoMessage() {}

func (x *ReportNetworkChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportNetworkChangeRequest.ProtoReflect.Descriptor instead.
func (*ReportNetworkChangeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{26}
}

func (x *ReportNetworkChangeRequest) GetAgentId() uint64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *ReportNetworkChangeRequest) GetNetworks() []*NetworkInterface {
	if x != nil {
		return x.Networks
	}
	return nil
}

// ReportNetworkChangeResponse 上报网络变化响应
type ReportNetworkChangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportNetworkChangeResponse) Reset() {
	*x = ReportNetworkChangeResponse{}
	mi := &file_pkg_proto_agent_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportNetworkChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportNetworkChangeResponse) ProtoMessage() {}

func (x *ReportNetworkChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportNetworkChangeResponse.ProtoReflect.Descriptor instead.
func (*ReportNetworkChangeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{27}
}

func (x *ReportNetworkChangeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportNetworkChangeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// SVCProxyData K8S Service 代理数据帧
// 首包携带连接参数（is_connect=true），后续包携带数据
type SVCProxyData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`                        // 目标命名空间（首包携带）
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // 目标 Service 名称（首包携带）
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`                                 // 目标端口（首包携带）
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`                                  // 数据载荷
	IsConnect     bool                   `protobuf:"varint,5,opt,name=is_connect,json=isConnect,proto3" json:"is_connect,omitempty"`      // 是否为连接请求（首包 true）
	IsClose       bool                   `protobuf:"varint,6,opt,name=is_close,json=isClose,proto3" json:"is_close,omitempty"`            // 是否为关闭通知
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`                                // 错误信息（如有）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SVCProxyData) Reset() {
	*x = SVCProxyData{}
	mi := &file_pkg_proto_agent_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SVCProxyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SVCProxyData) ProtoMessage() {}

func (x *SVCProxyData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SVCProxyData.ProtoReflect.Descriptor instead.
func (*SVCProxyData) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{28}
}

func (x *SVCProxyData) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SVCProxyData) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *SVCProxyData) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SVCProxyData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SVCProxyData) GetIsConnect() bool {
	if x != nil {
		return x.IsConnect
	}
	return false
}

func (x *SVCProxyData) GetIsClose() bool {
	if x != nil {
		return x.IsClose
	}
	return false
}

func (x *SVCProxyData) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_proto_agent_proto protoreflect.FileDescriptor

const file_pkg_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x15pkg/proto/agent.proto\x12\x12awecloud.signaling\"\xb7\x01\n" +
	"\n" +
	"SystemInfo\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x1d\n" +
	"\n" +
	"os_version\x18\x02 \x01(\tR\tosVersion\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\x12\x10\n" +
	"\x03cpu\x18\x05 \x01(\tR\x03cpu\x12\x1b\n" +
	"\tcpu_cores\x18\x06 \x01(\x05R\bcpuCores\x12\x1b\n" +
	"\tmemory_gb\x18\a \x01(\x05R\bmemoryGb\"d\n" +
	"\x10NetworkInterface\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x12\n" +
	"\x04mask\x18\x03 \x01(\tR\x04mask\x12\x18\n" +
	"\agateway\x18\x04 \x01(\tR\agateway\"\x9d\x01\n" +
	"\x14AgentRegisterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12?\n" +
	"\vsystem_info\x18\x04 \x01(\v2\x1e.awecloud.signaling.SystemInfoR\n" +
	"systemInfo\"\xa0\x01\n" +
	"\x15AgentRegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\x04R\aagentId\x12\x19\n" +
	"\bauth_key\x18\x04 \x01(\tR\aauthKey\x12\x1d\n" +
	"\n" +
	"server_url\x18\x05 \x01(\tR\tserverUrl\"\xa8\x01\n" +
	"\x18AgentAuthenticateRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x04R\aagentId\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12?\n" +
	"\vsystem_info\x18\x04 \x01(\v2\x1e.awecloud.signaling.SystemInfoR\n" +
	"systemInfo\"\x89\x01\n" +
	"\x19AgentAuthenticateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bauth_key\x18\x03 \x01(\tR\aauthKey\x12\x1d\n" +
	"\n" +
	"server_url\x18\x04 \x01(\tR\tserverUrl\"^\n" +
	"\rServiceStatus\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x18\n" +
	"\arunning\x18\x02 \x01(\bR\arunning\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"^\n" +
	"\rForwardStatus\x12\x1d\n" +
	"\n" +
	"forward_id\x18\x01 \x01(\tR\tforwardId\x12\x18\n" +
	"\arunning\x18\x02 \x01(\bR\arunning\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xbc\x04\n" +
	"\x15AgentHeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x04R\aagentId\x12\x1b\n" +
	"\ttunnel_ip\x18\x02 \x01(\tR\btunnelIp\x12)\n" +
	"\x10tunnel_connected\x18\x03 \x01(\bR\x0ftunnelConnected\x12H\n" +
	"\x0eservice_status\x18\x04 \x03(\v2!.awecloud.signaling.ServiceStatusR\rserviceStatus\x12H\n" +
	"\x0eforward_status\x18\x05 \x03(\v2!.awecloud.signaling.ForwardStatusR\rforwardStatus\x12\x1a\n" +
	"\bhostname\x18\x06 \x01(\tR\bhostname\x12\x18\n" +
	"\aruntime\x18\a \x01(\tR\aruntime\x12@\n" +
	"\bnetworks\x18\b \x03(\v2$.awecloud.signaling.NetworkInterfaceR\bnetworks\x12Y\n" +
	"\x14domain_registrations\x18\t \x03(\v2&.awecloud.signaling.DomainRegistrationR\x13domainRegistrations\x12Y\n" +
	"\x13discovered_services\x18\n" +
	" \x03(\v2(.awecloud.signaling.DiscoveredK8SServiceR\x12discoveredServices\"\xb6\x02\n" +
	"\x14DiscoveredK8SService\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x1d\n" +
	"\n" +
	"cluster_ip\x18\x03 \x01(\tR\tclusterIp\x125\n" +
	"\x05ports\x18\x04 \x03(\v2\x1f.awecloud.signaling.ServicePortR\x05ports\x12L\n" +
	"\x06labels\x18\x05 \x03(\v24.awecloud.signaling.DiscoveredK8SService.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Q\n" +
	"\vServicePort\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"\xf9\x01\n" +
	"\x12DomainRegistration\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1b\n" +
	"\ttarget_ip\x18\x03 \x01(\tR\btargetIp\x12\x1f\n" +
	"\vtarget_port\x18\x04 \x01(\x05R\n" +
	"targetPort\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12!\n" +
	"\fservice_name\x18\x06 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vendpoint_id\x18\a \x01(\tR\n" +
	"endpointId\x12\x17\n" +
	"\anode_id\x18\b \x01(\x04R\x06nodeId\"\x8f\x01\n" +
	"\rServiceConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vsource_addr\x18\x03 \x01(\tR\n" +
	"sourceAddr\x12\x1f\n" +
	"\vtarget_addr\x18\x04 \x01(\tR\n" +
	"targetAddr\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\"\xbd\x01\n" +
	"\rForwardConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vsource_addr\x18\x04 \x01(\tR\n" +
	"sourceAddr\x12\x1f\n" +
	"\vtarget_addr\x18\x05 \x01(\tR\n" +
	"targetAddr\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\"\xa2\x04\n" +
	"\x16AgentHeartbeatResponse\x12%\n" +
	"\x0econfig_version\x18\x01 \x01(\x03R\rconfigVersion\x12=\n" +
	"\bservices\x18\x02 \x03(\v2!.awecloud.signaling.ServiceConfigR\bservices\x12=\n" +
	"\bforwards\x18\x03 \x03(\v2!.awecloud.signaling.ForwardConfigR\bforwards\x12#\n" +
	"\rdomain_suffix\x18\x04 \x01(\tR\fdomainSuffix\x12J\n" +
	"\x0fk8s_permissions\x18\x05 \x03(\v2!.awecloud.signaling.K8SPermissionR\x0ek8sPermissions\x12`\n" +
	"\x17k8s_service_permissions\x18\x06 \x03(\v2(.awecloud.signaling.K8SServicePermissionR\x15k8sServicePermissions\x128\n" +
	"\x18request_immediate_report\x18\a \x01(\bR\x16requestImmediateReport\x12V\n" +
	"\x11capability_config\x18\b \x01(\v2).awecloud.signaling.AgentCapabilityConfigR\x10capabilityConfig\"\xbd\x05\n" +
	"\x15AgentCapabilityConfig\x12\x1f\n" +
	"\vssh_enabled\x18\x01 \x01(\bR\n" +
	"sshEnabled\x12&\n" +
	"\x0fssh_enabled_set\x18\x02 \x01(\bR\rsshEnabledSet\x12\x1f\n" +
	"\vk8s_enabled\x18\x03 \x01(\bR\n" +
	"k8sEnabled\x12&\n" +
	"\x0fk8s_enabled_set\x18\x04 \x01(\bR\rk8sEnabledSet\x12&\n" +
	"\x0fk8s_listen_port\x18\x05 \x01(\x05R\rk8sListenPort\x12-\n" +
	"\x13k8s_listen_port_set\x18\x06 \x01(\bR\x10k8sListenPortSet\x12$\n" +
	"\x0ek8s_api_server\x18\a \x01(\tR\fk8sApiServer\x12+\n" +
	"\x12k8s_api_server_set\x18\b \x01(\bR\x0fk8sApiServerSet\x12\x1f\n" +
	"\vsvc_enabled\x18\t \x01(\bR\n" +
	"svcEnabled\x12&\n" +
	"\x0fsvc_enabled_set\x18\n" +
	" \x01(\bR\rsvcEnabledSet\x12,\n" +
	"\x12svc_label_selector\x18\v \x01(\tR\x10svcLabelSelector\x123\n" +
	"\x16svc_label_selector_set\x18\f \x01(\bR\x13svcLabelSelectorSet\x12%\n" +
	"\x0esvc_namespaces\x18\r \x01(\tR\rsvcNamespaces\x12,\n" +
	"\x12svc_namespaces_set\x18\x0e \x01(\bR\x10svcNamespacesSet\x12/\n" +
	"\x14svc_listen_port_base\x18\x0f \x01(\x05R\x11svcListenPortBase\x126\n" +
	"\x18svc_listen_port_base_set\x18\x10 \x01(\bR\x14svcListenPortBaseSet\"\x9f\x01\n" +
	"\rK8SPermission\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x1d\n" +
	"\n" +
	"k8s_groups\x18\x03 \x03(\tR\tk8sGroups\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x04 \x03(\tR\n" +
	"namespaces\x12\x19\n" +
	"\bis_group\x18\x05 \x01(\bR\aisGroup\"\xac\x01\n" +
	"\x14K8SServicePermission\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x03 \x03(\tR\n" +
	"namespaces\x12#\n" +
	"\rservice_names\x18\x04 \x03(\tR\fserviceNames\x12\x19\n" +
	"\bis_group\x18\x05 \x01(\bR\aisGroup\"5\n" +
	"\x18GetRealtimeStatusRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x04R\aagentId\"\x8f\x02\n" +
	"\x19GetRealtimeStatusResponse\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x18\n" +
	"\aruntime\x18\x02 \x01(\tR\aruntime\x12@\n" +
	"\bnetworks\x18\x03 \x03(\v2$.awecloud.signaling.NetworkInterfaceR\bnetworks\x12\x1b\n" +
	"\ttunnel_ip\x18\x04 \x01(\tR\btunnelIp\x12)\n" +
	"\x10tunnel_connected\x18\x05 \x01(\bR\x0ftunnelConnected\x122\n" +
	"\x15tunnel_connected_time\x18\x06 \x01(\x03R\x13tunnelConnectedTime\"\x80\x01\n" +
	"\vProxyStatus\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12\x1b\n" +
	"\terror_msg\x18\x04 \x01(\tR\berrorMsg\"r\n" +
	"\x18ReportProxyStatusRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x04R\aagentId\x12;\n" +
	"\bstatuses\x18\x02 \x03(\v2\x1f.awecloud.signaling.ProxyStatusR\bstatuses\"O\n" +
	"\x19ReportProxyStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x90\x02\n" +
	"\rVisitorStatus\x12\x1d\n" +
	"\n" +
	"forward_id\x18\x01 \x01(\tR\tforwardId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12'\n" +
	"\x0fconfigured_addr\x18\x03 \x01(\tR\x0econfiguredAddr\x12\x1f\n" +
	"\vactual_addr\x18\x04 \x01(\tR\n" +
	"actualAddr\x12\x1d\n" +
	"\n" +
	"ip_changed\x18\x05 \x01(\bR\tipChanged\x12#\n" +
	"\rchange_reason\x18\x06 \x01(\tR\fchangeReason\x12\x1d\n" +
	"\n" +
	"error_code\x18\a \x01(\tR\terrorCode\x12\x1b\n" +
	"\terror_msg\x18\b \x01(\tR\berrorMsg\"v\n" +
	"\x1aReportVisitorStatusRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x04R\aagentId\x12=\n" +
	"\bstatuses\x18\x02 \x03(\v2!.awecloud.signaling.VisitorStatusR\bstatuses\"Q\n" +
	"\x1bReportVisitorStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"y\n" +
	"\x1aReportNetworkChangeRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x04R\aagentId\x12@\n" +
	"\bnetworks\x18\x02 \x03(\v2$.awecloud.signaling.NetworkInterfaceR\bnetworks\"Q\n" +
	"\x1bReportNetworkChangeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc7\x01\n" +
	"\fSVCProxyData\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"is_connect\x18\x05 \x01(\bR\tisConnect\x12\x19\n" +
	"\bis_close\x18\x06 \x01(\bR\aisClose\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error2\xec\x06\n" +
	"\fAgentService\x12_\n" +
	"\bRegister\x12(.awecloud.signaling.AgentRegisterRequest\x1a).awecloud.signaling.AgentRegisterResponse\x12k\n" +
	"\fAuthenticate\x12,.awecloud.signaling.AgentAuthenticateRequest\x1a-.awecloud.signaling.AgentAuthenticateResponse\x12f\n" +
	"\tHeartbeat\x12).awecloud.signaling.AgentHeartbeatRequest\x1a*.awecloud.signaling.AgentHeartbeatResponse(\x010\x01\x12p\n" +
	"\x11GetRealtimeStatus\x12,.awecloud.signaling.GetRealtimeStatusRequest\x1a-.awecloud.signaling.GetRealtimeStatusResponse\x12p\n" +
	"\x11ReportProxyStatus\x12,.awecloud.signaling.ReportProxyStatusRequest\x1a-.awecloud.signaling.ReportProxyStatusResponse\x12v\n" +
	"\x13ReportVisitorStatus\x12..awecloud.signaling.ReportVisitorStatusRequest\x1a/.awecloud.signaling.ReportVisitorStatusResponse\x12v\n" +
	"\x13ReportNetworkChange\x12..awecloud.signaling.ReportNetworkChangeRequest\x1a/.awecloud.signaling.ReportNetworkChangeResponse\x12R\n" +
	"\bSVCProxy\x12 .awecloud.signaling.SVCProxyData\x1a .awecloud.signaling.SVCProxyData(\x010\x01B<Z:github.com/open-beagle/awecloud-signaling-server/pkg/protob\x06proto3"

var (
	file_pkg_proto_agent_proto_rawDescOnce sync.Once
	file_pkg_proto_agent_proto_rawDescData []byte
)

func file_pkg_proto_agent_proto_rawDescGZIP() []byte {
	file_pkg_proto_agent_proto_rawDescOnce.Do(func() {
		file_pkg_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_agent_proto_rawDesc), len(file_pkg_proto_agent_proto_rawDesc)))
	})
	return file_pkg_proto_agent_proto_rawDescData
}

var file_pkg_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_pkg_proto_agent_proto_goTypes = []any{
	(*SystemInfo)(nil),                  // 0: awecloud.signaling.SystemInfo
	(*NetworkInterface)(nil),            // 1: awecloud.signaling.NetworkInterface
	(*AgentRegisterRequest)(nil),        // 2: awecloud.signaling.AgentRegisterRequest
	(*AgentRegisterResponse)(nil),       // 3: awecloud.signaling.AgentRegisterResponse
	(*AgentAuthenticateRequest)(nil),    // 4: awecloud.signaling.AgentAuthenticateRequest
	(*AgentAuthenticateResponse)(nil),   // 5: awecloud.signaling.AgentAuthenticateResponse
	(*ServiceStatus)(nil),               // 6: awecloud.signaling.ServiceStatus
	(*ForwardStatus)(nil),               // 7: awecloud.signaling.ForwardStatus
	(*AgentHeartbeatRequest)(nil),       // 8: awecloud.signaling.AgentHeartbeatRequest
	(*DiscoveredK8SService)(nil),        // 9: awecloud.signaling.DiscoveredK8SService
	(*ServicePort)(nil),                 // 10: awecloud.signaling.ServicePort
	(*DomainRegistration)(nil),          // 11: awecloud.signaling.DomainRegistration
	(*ServiceConfig)(nil),               // 12: awecloud.signaling.ServiceConfig
	(*ForwardConfig)(nil),               // 13: awecloud.signaling.ForwardConfig
	(*AgentHeartbeatResponse)(nil),      // 14: awecloud.signaling.AgentHeartbeatResponse
	(*AgentCapabilityConfig)(nil),       // 15: awecloud.signaling.AgentCapabilityConfig
	(*K8SPermission)(nil),               // 16: awecloud.signaling.K8SPermission
	(*K8SServicePermission)(nil),        // 17: awecloud.signaling.K8SServicePermission
	(*GetRealtimeStatusRequest)(nil),    // 18: awecloud.signaling.GetRealtimeStatusRequest
	(*GetRealtimeStatusResponse)(nil),   // 19: awecloud.signaling.GetRealtimeStatusResponse
	(*ProxyStatus)(nil),                 // 20: awecloud.signaling.ProxyStatus
	(*ReportProxyStatusRequest)(nil),    // 21: awecloud.signaling.ReportProxyStatusRequest
	(*ReportProxyStatusResponse)(nil),   // 22: awecloud.signaling.ReportProxyStatusResponse
	(*VisitorStatus)(nil),               // 23: awecloud.signaling.VisitorStatus
	(*ReportVisitorStatusRequest)(nil),  // 24: awecloud.signaling.ReportVisitorStatusRequest
	(*ReportVisitorStatusResponse)(nil), // 25: awecloud.signaling.ReportVisitorStatusResponse
	(*ReportNetworkChangeRequest)(nil),  // 26: awecloud.signaling.ReportNetworkChangeRequest
	(*ReportNetworkChangeResponse)(nil), // 27: awecloud.signaling.ReportNetworkChangeResponse
	(*SVCProxyData)(nil),                // 28: awecloud.signaling.SVCProxyData
	nil,                                 // 29: awecloud.signaling.DiscoveredK8SService.LabelsEntry
}
var file_pkg_proto_agent_proto_depIdxs = []int32{
	0,  // 0: awecloud.signaling.AgentRegisterRequest.system_info:type_name -> awecloud.signaling.SystemInfo
	0,  // 1: awecloud.signaling.AgentAuthenticateRequest.system_info:type_name -> awecloud.signaling.SystemInfo
	6,  // 2: awecloud.signaling.AgentHeartbeatRequest.service_status:type_name -> awecloud.signaling.ServiceStatus
	7,  // 3: awecloud.signaling.AgentHeartbeatRequest.forward_status:type_name -> awecloud.signaling.ForwardStatus
	1,  // 4: awecloud.signaling.AgentHeartbeatRequest.networks:type_name -> awecloud.signaling.NetworkInterface
	11, // 5: awecloud.signaling.AgentHeartbeatRequest.domain_registrations:type_name -> awecloud.signaling.DomainRegistration
	9,  // 6: awecloud.signaling.AgentHeartbeatRequest.discovered_services:type_name -> awecloud.signaling.DiscoveredK8SService
	10, // 7: awecloud.signaling.DiscoveredK8SService.ports:type_name -> awecloud.signaling.ServicePort
	29, // 8: awecloud.signaling.DiscoveredK8SService.labels:type_name -> awecloud.signaling.DiscoveredK8SService.LabelsEntry
	12, // 9: awecloud.signaling.AgentHeartbeatResponse.services:type_name -> awecloud.signaling.ServiceConfig
	13, // 10: awecloud.signaling.AgentHeartbeatResponse.forwards:type_name -> awecloud.signaling.ForwardConfig
	16, // 11: awecloud.signaling.AgentHeartbeatResponse.k8s_permissions:type_name -> awecloud.signaling.K8SPermission
	17, // 12: awecloud.signaling.AgentHeartbeatResponse.k8s_service_permissions:type_name -> awecloud.signaling.K8SServicePermission
	15, // 13: awecloud.signaling.AgentHeartbeatResponse.capability_config:type_name -> awecloud.signaling.AgentCapabilityConfig
	1,  // 14: awecloud.signaling.GetRealtimeStatusResponse.networks:type_name -> awecloud.signaling.NetworkInterface
	20, // 15: awecloud.signaling.ReportProxyStatusRequest.statuses:type_name -> awecloud.signaling.ProxyStatus
	23, // 16: awecloud.signaling.ReportVisitorStatusRequest.statuses:type_name -> awecloud.signaling.VisitorStatus
	1,  // 17: awecloud.signaling.ReportNetworkChangeRequest.networks:type_name -> awecloud.signaling.NetworkInterface
	2,  // 18: awecloud.signaling.AgentService.Register:input_type -> awecloud.signaling.AgentRegisterRequest
	4,  // 19: awecloud.signaling.AgentService.Authenticate:input_type -> awecloud.signaling.AgentAuthenticateRequest
	8,  // 20: awecloud.signaling.AgentService.Heartbeat:input_type -> awecloud.signaling.AgentHeartbeatRequest
	18, // 21: awecloud.signaling.AgentService.GetRealtimeStatus:input_type -> awecloud.signaling.GetRealtimeStatusRequest
	21, // 22: awecloud.signaling.AgentService.ReportProxyStatus:input_type -> awecloud.signaling.ReportProxyStatusRequest
	24, // 23: awecloud.signaling.AgentService.ReportVisitorStatus:input_type -> awecloud.signaling.ReportVisitorStatusRequest
	26, // 24: awecloud.signaling.AgentService.ReportNetworkChange:input_type -> awecloud.signaling.ReportNetworkChangeRequest
	28, // 25: awecloud.signaling.AgentService.SVCProxy:input_type -> awecloud.signaling.SVCProxyData
	3,  // 26: awecloud.signaling.AgentService.Register:output_type -> awecloud.signaling.AgentRegisterResponse
	5,  // 27: awecloud.signaling.AgentService.Authenticate:output_type -> awecloud.signaling.AgentAuthenticateResponse
	14, // 28: awecloud.signaling.AgentService.Heartbeat:output_type -> awecloud.signaling.AgentHeartbeatResponse
	19, // 29: awecloud.signaling.AgentService.GetRealtimeStatus:output_type -> awecloud.signaling.GetRealtimeStatusResponse
	22, // 30: awecloud.signaling.AgentService.ReportProxyStatus:output_type -> awecloud.signaling.ReportProxyStatusResponse
	25, // 31: awecloud.signaling.AgentService.ReportVisitorStatus:output_type -> awecloud.signaling.ReportVisitorStatusResponse
	27, // 32: awecloud.signaling.AgentService.ReportNetworkChange:output_type -> awecloud.signaling.ReportNetworkChangeResponse
	28, // 33: awecloud.signaling.AgentService.SVCProxy:output_type -> awecloud.signaling.SVCProxyData
	26, // [26:34] is the sub-list for method output_type
	18, // [18:26] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_pkg_proto_agent_proto_init() }
func file_pkg_proto_agent_proto_init() {
	if File_pkg_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_agent_proto_rawDesc), len(file_pkg_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_agent_proto_goTypes,
		DependencyIndexes: file_pkg_proto_agent_proto_depIdxs,
		MessageInfos:      file_pkg_proto_agent_proto_msgTypes,
	}.Build()
	File_pkg_proto_agent_proto = out.File
	file_pkg_proto_agent_proto_goTypes = nil
	file_pkg_proto_agent_proto_depIdxs = nil
}
