// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.3
// source: pkg/proto/desktop.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DesktopService_Authenticate_FullMethodName          = "/awecloud.signaling.DesktopService/Authenticate"
	DesktopService_Heartbeat_FullMethodName             = "/awecloud.signaling.DesktopService/Heartbeat"
	DesktopService_DataStream_FullMethodName            = "/awecloud.signaling.DesktopService/DataStream"
	DesktopService_GetAuthorizedHosts_FullMethodName    = "/awecloud.signaling.DesktopService/GetAuthorizedHosts"
	DesktopService_GetHostServices_FullMethodName       = "/awecloud.signaling.DesktopService/GetHostServices"
	DesktopService_GetMyDevices_FullMethodName          = "/awecloud.signaling.DesktopService/GetMyDevices"
	DesktopService_OfflineDevice_FullMethodName         = "/awecloud.signaling.DesktopService/OfflineDevice"
	DesktopService_DeleteDevice_FullMethodName          = "/awecloud.signaling.DesktopService/DeleteDevice"
	DesktopService_ToggleFavorite_FullMethodName        = "/awecloud.signaling.DesktopService/ToggleFavorite"
	DesktopService_GetFavoriteServices_FullMethodName   = "/awecloud.signaling.DesktopService/GetFavoriteServices"
	DesktopService_CheckSavedCredentials_FullMethodName = "/awecloud.signaling.DesktopService/CheckSavedCredentials"
	DesktopService_CreateLoginSession_FullMethodName    = "/awecloud.signaling.DesktopService/CreateLoginSession"
	DesktopService_WaitForLoginResult_FullMethodName    = "/awecloud.signaling.DesktopService/WaitForLoginResult"
	DesktopService_Logout_FullMethodName                = "/awecloud.signaling.DesktopService/Logout"
	DesktopService_ResolveDomain_FullMethodName         = "/awecloud.signaling.DesktopService/ResolveDomain"
	DesktopService_GetResources_FullMethodName          = "/awecloud.signaling.DesktopService/GetResources"
	DesktopService_GetDomainList_FullMethodName         = "/awecloud.signaling.DesktopService/GetDomainList"
)

// DesktopServiceClient is the client API for DesktopService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DesktopService Desktop 管理服务
type DesktopServiceClient interface {
	// 认证 - Desktop 用设备凭证认证
	Authenticate(ctx context.Context, in *DesktopAuthenticateRequest, opts ...grpc.CallOption) (*DesktopAuthenticateResponse, error)
	// 心跳 - 保持连接状态（纯心跳，不携带业务数据）
	Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DesktopHeartbeatRequest, DesktopHeartbeatResponse], error)
	// 数据流 - Server 主动推送业务数据变更
	DataStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DesktopDataRequest, DesktopDataResponse], error)
	// 获取已授权主机列表
	GetAuthorizedHosts(ctx context.Context, in *GetAuthorizedHostsRequest, opts ...grpc.CallOption) (*GetAuthorizedHostsResponse, error)
	// 获取指定主机的服务列表
	GetHostServices(ctx context.Context, in *GetHostServicesRequest, opts ...grpc.CallOption) (*GetHostServicesResponse, error)
	// 获取我的设备列表
	GetMyDevices(ctx context.Context, in *GetMyDevicesRequest, opts ...grpc.CallOption) (*GetMyDevicesResponse, error)
	// 设备下线
	OfflineDevice(ctx context.Context, in *OfflineDeviceRequest, opts ...grpc.CallOption) (*OfflineDeviceResponse, error)
	// 删除设备
	DeleteDevice(ctx context.Context, in *DeleteDeviceRequest, opts ...grpc.CallOption) (*DeleteDeviceResponse, error)
	// 切换服务收藏状态
	ToggleFavorite(ctx context.Context, in *ToggleFavoriteRequest, opts ...grpc.CallOption) (*ToggleFavoriteResponse, error)
	// 获取收藏的服务列表
	GetFavoriteServices(ctx context.Context, in *GetFavoriteServicesRequest, opts ...grpc.CallOption) (*GetFavoriteServicesResponse, error)
	// 检查保存的凭据（用于自动登录）
	CheckSavedCredentials(ctx context.Context, in *CheckSavedCredentialsRequest, opts ...grpc.CallOption) (*CheckSavedCredentialsResponse, error)
	// 创建登录会话 - 返回 session_id 和 login_url
	CreateLoginSession(ctx context.Context, in *CreateLoginSessionRequest, opts ...grpc.CallOption) (*CreateLoginSessionResponse, error)
	// 等待登录结果 - 通过 gRPC 双向流等待登录完成
	WaitForLoginResult(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WaitForLoginResultRequest, WaitForLoginResultResponse], error)
	// 注销 - Desktop 安全离场
	Logout(ctx context.Context, in *DesktopLogoutRequest, opts ...grpc.CallOption) (*DesktopLogoutResponse, error)
	// 域名解析 - Desktop 查询域名对应的 Agent 地址（域名后缀可配置，默认 .beagle）
	ResolveDomain(ctx context.Context, in *ResolveDomainRequest, opts ...grpc.CallOption) (*ResolveDomainResponse, error)
	// 资源发现 - Desktop 查询可访问的资源列表
	GetResources(ctx context.Context, in *GetResourcesRequest, opts ...grpc.CallOption) (*GetResourcesResponse, error)
	// 获取域名列表 - Desktop 查询可访问的域名记录（按类型分类）
	GetDomainList(ctx context.Context, in *GetDomainListRequest, opts ...grpc.CallOption) (*GetDomainListResponse, error)
}

type desktopServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDesktopServiceClient(cc grpc.ClientConnInterface) DesktopServiceClient {
	return &desktopServiceClient{cc}
}

func (c *desktopServiceClient) Authenticate(ctx context.Context, in *DesktopAuthenticateRequest, opts ...grpc.CallOption) (*DesktopAuthenticateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesktopAuthenticateResponse)
	err := c.cc.Invoke(ctx, DesktopService_Authenticate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *desktopServiceClient) Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DesktopHeartbeatRequest, DesktopHeartbeatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DesktopService_ServiceDesc.Streams[0], DesktopService_Heartbeat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DesktopHeartbeatRequest, DesktopHeartbeatResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DesktopService_HeartbeatClient = grpc.BidiStreamingClient[DesktopHeartbeatRequest, DesktopHeartbeatResponse]

func (c *desktopServiceClient) DataStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DesktopDataRequest, DesktopDataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DesktopService_ServiceDesc.Streams[1], DesktopService_DataStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DesktopDataRequest, DesktopDataResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DesktopService_DataStreamClient = grpc.BidiStreamingClient[DesktopDataRequest, DesktopDataResponse]

func (c *desktopServiceClient) GetAuthorizedHosts(ctx context.Context, in *GetAuthorizedHostsRequest, opts ...grpc.CallOption) (*GetAuthorizedHostsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuthorizedHostsResponse)
	err := c.cc.Invoke(ctx, DesktopService_GetAuthorizedHosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *desktopServiceClient) GetHostServices(ctx context.Context, in *GetHostServicesRequest, opts ...grpc.CallOption) (*GetHostServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHostServicesResponse)
	err := c.cc.Invoke(ctx, DesktopService_GetHostServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *desktopServiceClient) GetMyDevices(ctx context.Context, in *GetMyDevicesRequest, opts ...grpc.CallOption) (*GetMyDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyDevicesResponse)
	err := c.cc.Invoke(ctx, DesktopService_GetMyDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *desktopServiceClient) OfflineDevice(ctx context.Context, in *OfflineDeviceRequest, opts ...grpc.CallOption) (*OfflineDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OfflineDeviceResponse)
	err := c.cc.Invoke(ctx, DesktopService_OfflineDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *desktopServiceClient) DeleteDevice(ctx context.Context, in *DeleteDeviceRequest, opts ...grpc.CallOption) (*DeleteDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDeviceResponse)
	err := c.cc.Invoke(ctx, DesktopService_DeleteDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *desktopServiceClient) ToggleFavorite(ctx context.Context, in *ToggleFavoriteRequest, opts ...grpc.CallOption) (*ToggleFavoriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToggleFavoriteResponse)
	err := c.cc.Invoke(ctx, DesktopService_ToggleFavorite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *desktopServiceClient) GetFavoriteServices(ctx context.Context, in *GetFavoriteServicesRequest, opts ...grpc.CallOption) (*GetFavoriteServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFavoriteServicesResponse)
	err := c.cc.Invoke(ctx, DesktopService_GetFavoriteServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *desktopServiceClient) CheckSavedCredentials(ctx context.Context, in *CheckSavedCredentialsRequest, opts ...grpc.CallOption) (*CheckSavedCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckSavedCredentialsResponse)
	err := c.cc.Invoke(ctx, DesktopService_CheckSavedCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *desktopServiceClient) CreateLoginSession(ctx context.Context, in *CreateLoginSessionRequest, opts ...grpc.CallOption) (*CreateLoginSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLoginSessionResponse)
	err := c.cc.Invoke(ctx, DesktopService_CreateLoginSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *desktopServiceClient) WaitForLoginResult(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WaitForLoginResultRequest, WaitForLoginResultResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DesktopService_ServiceDesc.Streams[2], DesktopService_WaitForLoginResult_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WaitForLoginResultRequest, WaitForLoginResultResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DesktopService_WaitForLoginResultClient = grpc.BidiStreamingClient[WaitForLoginResultRequest, WaitForLoginResultResponse]

func (c *desktopServiceClient) Logout(ctx context.Context, in *DesktopLogoutRequest, opts ...grpc.CallOption) (*DesktopLogoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesktopLogoutResponse)
	err := c.cc.Invoke(ctx, DesktopService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *desktopServiceClient) ResolveDomain(ctx context.Context, in *ResolveDomainRequest, opts ...grpc.CallOption) (*ResolveDomainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveDomainResponse)
	err := c.cc.Invoke(ctx, DesktopService_ResolveDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *desktopServiceClient) GetResources(ctx context.Context, in *GetResourcesRequest, opts ...grpc.CallOption) (*GetResourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResourcesResponse)
	err := c.cc.Invoke(ctx, DesktopService_GetResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *desktopServiceClient) GetDomainList(ctx context.Context, in *GetDomainListRequest, opts ...grpc.CallOption) (*GetDomainListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDomainListResponse)
	err := c.cc.Invoke(ctx, DesktopService_GetDomainList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DesktopServiceServer is the server API for DesktopService service.
// All implementations must embed UnimplementedDesktopServiceServer
// for forward compatibility.
//
// DesktopService Desktop 管理服务
type DesktopServiceServer interface {
	// 认证 - Desktop 用设备凭证认证
	Authenticate(context.Context, *DesktopAuthenticateRequest) (*DesktopAuthenticateResponse, error)
	// 心跳 - 保持连接状态（纯心跳，不携带业务数据）
	Heartbeat(grpc.BidiStreamingServer[DesktopHeartbeatRequest, DesktopHeartbeatResponse]) error
	// 数据流 - Server 主动推送业务数据变更
	DataStream(grpc.BidiStreamingServer[DesktopDataRequest, DesktopDataResponse]) error
	// 获取已授权主机列表
	GetAuthorizedHosts(context.Context, *GetAuthorizedHostsRequest) (*GetAuthorizedHostsResponse, error)
	// 获取指定主机的服务列表
	GetHostServices(context.Context, *GetHostServicesRequest) (*GetHostServicesResponse, error)
	// 获取我的设备列表
	GetMyDevices(context.Context, *GetMyDevicesRequest) (*GetMyDevicesResponse, error)
	// 设备下线
	OfflineDevice(context.Context, *OfflineDeviceRequest) (*OfflineDeviceResponse, error)
	// 删除设备
	DeleteDevice(context.Context, *DeleteDeviceRequest) (*DeleteDeviceResponse, error)
	// 切换服务收藏状态
	ToggleFavorite(context.Context, *ToggleFavoriteRequest) (*ToggleFavoriteResponse, error)
	// 获取收藏的服务列表
	GetFavoriteServices(context.Context, *GetFavoriteServicesRequest) (*GetFavoriteServicesResponse, error)
	// 检查保存的凭据（用于自动登录）
	CheckSavedCredentials(context.Context, *CheckSavedCredentialsRequest) (*CheckSavedCredentialsResponse, error)
	// 创建登录会话 - 返回 session_id 和 login_url
	CreateLoginSession(context.Context, *CreateLoginSessionRequest) (*CreateLoginSessionResponse, error)
	// 等待登录结果 - 通过 gRPC 双向流等待登录完成
	WaitForLoginResult(grpc.BidiStreamingServer[WaitForLoginResultRequest, WaitForLoginResultResponse]) error
	// 注销 - Desktop 安全离场
	Logout(context.Context, *DesktopLogoutRequest) (*DesktopLogoutResponse, error)
	// 域名解析 - Desktop 查询域名对应的 Agent 地址（域名后缀可配置，默认 .beagle）
	ResolveDomain(context.Context, *ResolveDomainRequest) (*ResolveDomainResponse, error)
	// 资源发现 - Desktop 查询可访问的资源列表
	GetResources(context.Context, *GetResourcesRequest) (*GetResourcesResponse, error)
	// 获取域名列表 - Desktop 查询可访问的域名记录（按类型分类）
	GetDomainList(context.Context, *GetDomainListRequest) (*GetDomainListResponse, error)
	mustEmbedUnimplementedDesktopServiceServer()
}

// UnimplementedDesktopServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDesktopServiceServer struct{}

func (UnimplementedDesktopServiceServer) Authenticate(context.Context, *DesktopAuthenticateRequest) (*DesktopAuthenticateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedDesktopServiceServer) Heartbeat(grpc.BidiStreamingServer[DesktopHeartbeatRequest, DesktopHeartbeatResponse]) error {
	return status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedDesktopServiceServer) DataStream(grpc.BidiStreamingServer[DesktopDataRequest, DesktopDataResponse]) error {
	return status.Error(codes.Unimplemented, "method DataStream not implemented")
}
func (UnimplementedDesktopServiceServer) GetAuthorizedHosts(context.Context, *GetAuthorizedHostsRequest) (*GetAuthorizedHostsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuthorizedHosts not implemented")
}
func (UnimplementedDesktopServiceServer) GetHostServices(context.Context, *GetHostServicesRequest) (*GetHostServicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHostServices not implemented")
}
func (UnimplementedDesktopServiceServer) GetMyDevices(context.Context, *GetMyDevicesRequest) (*GetMyDevicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyDevices not implemented")
}
func (UnimplementedDesktopServiceServer) OfflineDevice(context.Context, *OfflineDeviceRequest) (*OfflineDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OfflineDevice not implemented")
}
func (UnimplementedDesktopServiceServer) DeleteDevice(context.Context, *DeleteDeviceRequest) (*DeleteDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDevice not implemented")
}
func (UnimplementedDesktopServiceServer) ToggleFavorite(context.Context, *ToggleFavoriteRequest) (*ToggleFavoriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ToggleFavorite not implemented")
}
func (UnimplementedDesktopServiceServer) GetFavoriteServices(context.Context, *GetFavoriteServicesRequest) (*GetFavoriteServicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFavoriteServices not implemented")
}
func (UnimplementedDesktopServiceServer) CheckSavedCredentials(context.Context, *CheckSavedCredentialsRequest) (*CheckSavedCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckSavedCredentials not implemented")
}
func (UnimplementedDesktopServiceServer) CreateLoginSession(context.Context, *CreateLoginSessionRequest) (*CreateLoginSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLoginSession not implemented")
}
func (UnimplementedDesktopServiceServer) WaitForLoginResult(grpc.BidiStreamingServer[WaitForLoginResultRequest, WaitForLoginResultResponse]) error {
	return status.Error(codes.Unimplemented, "method WaitForLoginResult not implemented")
}
func (UnimplementedDesktopServiceServer) Logout(context.Context, *DesktopLogoutRequest) (*DesktopLogoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedDesktopServiceServer) ResolveDomain(context.Context, *ResolveDomainRequest) (*ResolveDomainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveDomain not implemented")
}
func (UnimplementedDesktopServiceServer) GetResources(context.Context, *GetResourcesRequest) (*GetResourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResources not implemented")
}
func (UnimplementedDesktopServiceServer) GetDomainList(context.Context, *GetDomainListRequest) (*GetDomainListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDomainList not implemented")
}
func (UnimplementedDesktopServiceServer) mustEmbedUnimplementedDesktopServiceServer() {}
func (UnimplementedDesktopServiceServer) testEmbeddedByValue()                        {}

// UnsafeDesktopServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DesktopServiceServer will
// result in compilation errors.
type UnsafeDesktopServiceServer interface {
	mustEmbedUnimplementedDesktopServiceServer()
}

func RegisterDesktopServiceServer(s grpc.ServiceRegistrar, srv DesktopServiceServer) {
	// If the following call panics, it indicates UnimplementedDesktopServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DesktopService_ServiceDesc, srv)
}

func _DesktopService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesktopAuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesktopService_Authenticate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopServiceServer).Authenticate(ctx, req.(*DesktopAuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesktopService_Heartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DesktopServiceServer).Heartbeat(&grpc.GenericServerStream[DesktopHeartbeatRequest, DesktopHeartbeatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DesktopService_HeartbeatServer = grpc.BidiStreamingServer[DesktopHeartbeatRequest, DesktopHeartbeatResponse]

func _DesktopService_DataStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DesktopServiceServer).DataStream(&grpc.GenericServerStream[DesktopDataRequest, DesktopDataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DesktopService_DataStreamServer = grpc.BidiStreamingServer[DesktopDataRequest, DesktopDataResponse]

func _DesktopService_GetAuthorizedHosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthorizedHostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopServiceServer).GetAuthorizedHosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesktopService_GetAuthorizedHosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopServiceServer).GetAuthorizedHosts(ctx, req.(*GetAuthorizedHostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesktopService_GetHostServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopServiceServer).GetHostServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesktopService_GetHostServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopServiceServer).GetHostServices(ctx, req.(*GetHostServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesktopService_GetMyDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopServiceServer).GetMyDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesktopService_GetMyDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopServiceServer).GetMyDevices(ctx, req.(*GetMyDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesktopService_OfflineDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OfflineDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopServiceServer).OfflineDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesktopService_OfflineDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopServiceServer).OfflineDevice(ctx, req.(*OfflineDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesktopService_DeleteDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopServiceServer).DeleteDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesktopService_DeleteDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopServiceServer).DeleteDevice(ctx, req.(*DeleteDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesktopService_ToggleFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleFavoriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopServiceServer).ToggleFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesktopService_ToggleFavorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopServiceServer).ToggleFavorite(ctx, req.(*ToggleFavoriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesktopService_GetFavoriteServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFavoriteServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopServiceServer).GetFavoriteServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesktopService_GetFavoriteServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopServiceServer).GetFavoriteServices(ctx, req.(*GetFavoriteServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesktopService_CheckSavedCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckSavedCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopServiceServer).CheckSavedCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesktopService_CheckSavedCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopServiceServer).CheckSavedCredentials(ctx, req.(*CheckSavedCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesktopService_CreateLoginSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLoginSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopServiceServer).CreateLoginSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesktopService_CreateLoginSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopServiceServer).CreateLoginSession(ctx, req.(*CreateLoginSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesktopService_WaitForLoginResult_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DesktopServiceServer).WaitForLoginResult(&grpc.GenericServerStream[WaitForLoginResultRequest, WaitForLoginResultResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DesktopService_WaitForLoginResultServer = grpc.BidiStreamingServer[WaitForLoginResultRequest, WaitForLoginResultResponse]

func _DesktopService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesktopLogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesktopService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopServiceServer).Logout(ctx, req.(*DesktopLogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesktopService_ResolveDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopServiceServer).ResolveDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesktopService_ResolveDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopServiceServer).ResolveDomain(ctx, req.(*ResolveDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesktopService_GetResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopServiceServer).GetResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesktopService_GetResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopServiceServer).GetResources(ctx, req.(*GetResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesktopService_GetDomainList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDomainListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopServiceServer).GetDomainList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesktopService_GetDomainList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopServiceServer).GetDomainList(ctx, req.(*GetDomainListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DesktopService_ServiceDesc is the grpc.ServiceDesc for DesktopService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DesktopService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "awecloud.signaling.DesktopService",
	HandlerType: (*DesktopServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _DesktopService_Authenticate_Handler,
		},
		{
			MethodName: "GetAuthorizedHosts",
			Handler:    _DesktopService_GetAuthorizedHosts_Handler,
		},
		{
			MethodName: "GetHostServices",
			Handler:    _DesktopService_GetHostServices_Handler,
		},
		{
			MethodName: "GetMyDevices",
			Handler:    _DesktopService_GetMyDevices_Handler,
		},
		{
			MethodName: "OfflineDevice",
			Handler:    _DesktopService_OfflineDevice_Handler,
		},
		{
			MethodName: "DeleteDevice",
			Handler:    _DesktopService_DeleteDevice_Handler,
		},
		{
			MethodName: "ToggleFavorite",
			Handler:    _DesktopService_ToggleFavorite_Handler,
		},
		{
			MethodName: "GetFavoriteServices",
			Handler:    _DesktopService_GetFavoriteServices_Handler,
		},
		{
			MethodName: "CheckSavedCredentials",
			Handler:    _DesktopService_CheckSavedCredentials_Handler,
		},
		{
			MethodName: "CreateLoginSession",
			Handler:    _DesktopService_CreateLoginSession_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _DesktopService_Logout_Handler,
		},
		{
			MethodName: "ResolveDomain",
			Handler:    _DesktopService_ResolveDomain_Handler,
		},
		{
			MethodName: "GetResources",
			Handler:    _DesktopService_GetResources_Handler,
		},
		{
			MethodName: "GetDomainList",
			Handler:    _DesktopService_GetDomainList_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Heartbeat",
			Handler:       _DesktopService_Heartbeat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "DataStream",
			Handler:       _DesktopService_DataStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "WaitForLoginResult",
			Handler:       _DesktopService_WaitForLoginResult_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/proto/desktop.proto",
}
