// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.3
// source: pkg/proto/desktop.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DesktopService_Login_FullMethodName        = "/awecloud.signaling.DesktopService/Login"
	DesktopService_Authenticate_FullMethodName = "/awecloud.signaling.DesktopService/Authenticate"
	DesktopService_Heartbeat_FullMethodName    = "/awecloud.signaling.DesktopService/Heartbeat"
)

// DesktopServiceClient is the client API for DesktopService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DesktopService Desktop 管理服务
type DesktopServiceClient interface {
	// 首次登录 - Desktop 用 Client 凭证登录
	Login(ctx context.Context, in *DesktopLoginRequest, opts ...grpc.CallOption) (*DesktopLoginResponse, error)
	// 认证 - Desktop 用设备凭证认证
	Authenticate(ctx context.Context, in *DesktopAuthenticateRequest, opts ...grpc.CallOption) (*DesktopAuthenticateResponse, error)
	// 心跳 - 保持连接状态
	Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DesktopHeartbeatRequest, DesktopHeartbeatResponse], error)
}

type desktopServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDesktopServiceClient(cc grpc.ClientConnInterface) DesktopServiceClient {
	return &desktopServiceClient{cc}
}

func (c *desktopServiceClient) Login(ctx context.Context, in *DesktopLoginRequest, opts ...grpc.CallOption) (*DesktopLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesktopLoginResponse)
	err := c.cc.Invoke(ctx, DesktopService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *desktopServiceClient) Authenticate(ctx context.Context, in *DesktopAuthenticateRequest, opts ...grpc.CallOption) (*DesktopAuthenticateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesktopAuthenticateResponse)
	err := c.cc.Invoke(ctx, DesktopService_Authenticate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *desktopServiceClient) Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DesktopHeartbeatRequest, DesktopHeartbeatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DesktopService_ServiceDesc.Streams[0], DesktopService_Heartbeat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DesktopHeartbeatRequest, DesktopHeartbeatResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DesktopService_HeartbeatClient = grpc.BidiStreamingClient[DesktopHeartbeatRequest, DesktopHeartbeatResponse]

// DesktopServiceServer is the server API for DesktopService service.
// All implementations must embed UnimplementedDesktopServiceServer
// for forward compatibility.
//
// DesktopService Desktop 管理服务
type DesktopServiceServer interface {
	// 首次登录 - Desktop 用 Client 凭证登录
	Login(context.Context, *DesktopLoginRequest) (*DesktopLoginResponse, error)
	// 认证 - Desktop 用设备凭证认证
	Authenticate(context.Context, *DesktopAuthenticateRequest) (*DesktopAuthenticateResponse, error)
	// 心跳 - 保持连接状态
	Heartbeat(grpc.BidiStreamingServer[DesktopHeartbeatRequest, DesktopHeartbeatResponse]) error
	mustEmbedUnimplementedDesktopServiceServer()
}

// UnimplementedDesktopServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDesktopServiceServer struct{}

func (UnimplementedDesktopServiceServer) Login(context.Context, *DesktopLoginRequest) (*DesktopLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedDesktopServiceServer) Authenticate(context.Context, *DesktopAuthenticateRequest) (*DesktopAuthenticateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedDesktopServiceServer) Heartbeat(grpc.BidiStreamingServer[DesktopHeartbeatRequest, DesktopHeartbeatResponse]) error {
	return status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedDesktopServiceServer) mustEmbedUnimplementedDesktopServiceServer() {}
func (UnimplementedDesktopServiceServer) testEmbeddedByValue()                        {}

// UnsafeDesktopServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DesktopServiceServer will
// result in compilation errors.
type UnsafeDesktopServiceServer interface {
	mustEmbedUnimplementedDesktopServiceServer()
}

func RegisterDesktopServiceServer(s grpc.ServiceRegistrar, srv DesktopServiceServer) {
	// If the following call panics, it indicates UnimplementedDesktopServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DesktopService_ServiceDesc, srv)
}

func _DesktopService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesktopLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesktopService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopServiceServer).Login(ctx, req.(*DesktopLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesktopService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesktopAuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesktopService_Authenticate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopServiceServer).Authenticate(ctx, req.(*DesktopAuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesktopService_Heartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DesktopServiceServer).Heartbeat(&grpc.GenericServerStream[DesktopHeartbeatRequest, DesktopHeartbeatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DesktopService_HeartbeatServer = grpc.BidiStreamingServer[DesktopHeartbeatRequest, DesktopHeartbeatResponse]

// DesktopService_ServiceDesc is the grpc.ServiceDesc for DesktopService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DesktopService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "awecloud.signaling.DesktopService",
	HandlerType: (*DesktopServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _DesktopService_Login_Handler,
		},
		{
			MethodName: "Authenticate",
			Handler:    _DesktopService_Authenticate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Heartbeat",
			Handler:       _DesktopService_Heartbeat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/proto/desktop.proto",
}
