// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: pkg/proto/endpoint.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EndpointRegisterRequest Endpoint 注册请求
type EndpointRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`     // 注册令牌（ep_ 前缀，Server 生成）
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`       // Endpoint 名称（如 hostname）
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"` // Endpoint 版本号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointRegisterRequest) Reset() {
	*x = EndpointRegisterRequest{}
	mi := &file_pkg_proto_endpoint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointRegisterRequest) ProtoMessage() {}

func (x *EndpointRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_endpoint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointRegisterRequest.ProtoReflect.Descriptor instead.
func (*EndpointRegisterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_endpoint_proto_rawDescGZIP(), []int{0}
}

func (x *EndpointRegisterRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EndpointRegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EndpointRegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// EndpointRegisterResponse Endpoint 注册响应
type EndpointRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                        // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                         // 响应消息
	EndpointId    string                 `protobuf:"bytes,3,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"` // Endpoint ID（Agent 分配）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointRegisterResponse) Reset() {
	*x = EndpointRegisterResponse{}
	mi := &file_pkg_proto_endpoint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointRegisterResponse) ProtoMessage() {}

func (x *EndpointRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_endpoint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointRegisterResponse.ProtoReflect.Descriptor instead.
func (*EndpointRegisterResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_endpoint_proto_rawDescGZIP(), []int{1}
}

func (x *EndpointRegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EndpointRegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EndpointRegisterResponse) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

// EndpointHeartbeatRequest Endpoint 心跳请求
type EndpointHeartbeatRequest struct {
	state              protoimpl.MessageState    `protogen:"open.v1"`
	Token              string                    `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                                                     // 注册令牌（用于身份验证）
	Name               string                    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                       // Endpoint 名称
	Capabilities       []*EndpointCapabilityInfo `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`                                       // 启用的能力列表
	DiscoveredServices []*DiscoveredK8SService   `protobuf:"bytes,4,rep,name=discovered_services,json=discoveredServices,proto3" json:"discovered_services,omitempty"` // Endpoint 发现的 K8S Service
	// SSH 能力配置（从 Endpoint 自动检测）
	SshUsers []string `protobuf:"bytes,7,rep,name=ssh_users,json=sshUsers,proto3" json:"ssh_users,omitempty"` // 允许的 SSH 用户列表
	// K8S API 能力配置
	K8SapiApiServer string `protobuf:"bytes,8,opt,name=k8sapi_api_server,json=k8sapiApiServer,proto3" json:"k8sapi_api_server,omitempty"` // K8S API Server 地址
	// K8S Service 能力配置
	K8SserviceLabelSelector string   `protobuf:"bytes,9,opt,name=k8sservice_label_selector,json=k8sserviceLabelSelector,proto3" json:"k8sservice_label_selector,omitempty"` // 标签选择器
	K8SserviceNamespaces    []string `protobuf:"bytes,10,rep,name=k8sservice_namespaces,json=k8sserviceNamespaces,proto3" json:"k8sservice_namespaces,omitempty"`           // 命名空间列表
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *EndpointHeartbeatRequest) Reset() {
	*x = EndpointHeartbeatRequest{}
	mi := &file_pkg_proto_endpoint_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointHeartbeatRequest) ProtoMessage() {}

func (x *EndpointHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_endpoint_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*EndpointHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_endpoint_proto_rawDescGZIP(), []int{2}
}

func (x *EndpointHeartbeatRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EndpointHeartbeatRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EndpointHeartbeatRequest) GetCapabilities() []*EndpointCapabilityInfo {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *EndpointHeartbeatRequest) GetDiscoveredServices() []*DiscoveredK8SService {
	if x != nil {
		return x.DiscoveredServices
	}
	return nil
}

func (x *EndpointHeartbeatRequest) GetSshUsers() []string {
	if x != nil {
		return x.SshUsers
	}
	return nil
}

func (x *EndpointHeartbeatRequest) GetK8SapiApiServer() string {
	if x != nil {
		return x.K8SapiApiServer
	}
	return ""
}

func (x *EndpointHeartbeatRequest) GetK8SserviceLabelSelector() string {
	if x != nil {
		return x.K8SserviceLabelSelector
	}
	return ""
}

func (x *EndpointHeartbeatRequest) GetK8SserviceNamespaces() []string {
	if x != nil {
		return x.K8SserviceNamespaces
	}
	return nil
}

// EndpointCapabilityInfo Endpoint 单项能力信息
type EndpointCapabilityInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                            // 能力类型：ssh / k8sapi / k8sservice
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`                            // SSH 内网地址（SSH 类型时）
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`                           // SSH 端口（SSH 类型时，默认 22）
	ApiServer     string                 `protobuf:"bytes,4,opt,name=api_server,json=apiServer,proto3" json:"api_server,omitempty"` // K8S API Server 地址（K8SAPI 类型时）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointCapabilityInfo) Reset() {
	*x = EndpointCapabilityInfo{}
	mi := &file_pkg_proto_endpoint_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointCapabilityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointCapabilityInfo) ProtoMessage() {}

func (x *EndpointCapabilityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_endpoint_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointCapabilityInfo.ProtoReflect.Descriptor instead.
func (*EndpointCapabilityInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_endpoint_proto_rawDescGZIP(), []int{3}
}

func (x *EndpointCapabilityInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EndpointCapabilityInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *EndpointCapabilityInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *EndpointCapabilityInfo) GetApiServer() string {
	if x != nil {
		return x.ApiServer
	}
	return ""
}

// EndpointHeartbeatResponse Endpoint 心跳响应
type EndpointHeartbeatResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Success             bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                                     // 是否成功
	Message             string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                                      // 响应消息
	ShellRequests       []*ShellRequest        `protobuf:"bytes,3,rep,name=shell_requests,json=shellRequests,proto3" json:"shell_requests,omitempty"`                     // Shell 请求通知
	K8SapiProxyRequests []*K8SAPIProxyRequest  `protobuf:"bytes,4,rep,name=k8sapi_proxy_requests,json=k8sapiProxyRequests,proto3" json:"k8sapi_proxy_requests,omitempty"` // K8S API 代理请求通知
	SvcProxyRequests    []*SVCProxyRequest     `protobuf:"bytes,5,rep,name=svc_proxy_requests,json=svcProxyRequests,proto3" json:"svc_proxy_requests,omitempty"`          // K8S Service 代理请求通知
	// Server 下发的能力配置（由 Web 界面管理，Endpoint 应以此为准）
	SshEnabled           bool   `protobuf:"varint,10,opt,name=ssh_enabled,json=sshEnabled,proto3" json:"ssh_enabled,omitempty"`                                 // SSH 能力是否启用
	SshEnabledSet        bool   `protobuf:"varint,11,opt,name=ssh_enabled_set,json=sshEnabledSet,proto3" json:"ssh_enabled_set,omitempty"`                      // ssh_enabled 是否有效（false 表示未下发）
	K8SapiEnabled        bool   `protobuf:"varint,12,opt,name=k8sapi_enabled,json=k8sapiEnabled,proto3" json:"k8sapi_enabled,omitempty"`                        // K8S API 能力是否启用
	K8SapiEnabledSet     bool   `protobuf:"varint,13,opt,name=k8sapi_enabled_set,json=k8sapiEnabledSet,proto3" json:"k8sapi_enabled_set,omitempty"`             // k8sapi_enabled 是否有效
	K8SapiApiServer      string `protobuf:"bytes,14,opt,name=k8sapi_api_server,json=k8sapiApiServer,proto3" json:"k8sapi_api_server,omitempty"`                 // K8S API Server 地址（Server 存储的值）
	K8SserviceEnabled    bool   `protobuf:"varint,15,opt,name=k8sservice_enabled,json=k8sserviceEnabled,proto3" json:"k8sservice_enabled,omitempty"`            // K8S Service 能力是否启用
	K8SserviceEnabledSet bool   `protobuf:"varint,16,opt,name=k8sservice_enabled_set,json=k8sserviceEnabledSet,proto3" json:"k8sservice_enabled_set,omitempty"` // k8sservice_enabled 是否有效
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *EndpointHeartbeatResponse) Reset() {
	*x = EndpointHeartbeatResponse{}
	mi := &file_pkg_proto_endpoint_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointHeartbeatResponse) ProtoMessage() {}

func (x *EndpointHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_endpoint_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*EndpointHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_endpoint_proto_rawDescGZIP(), []int{4}
}

func (x *EndpointHeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EndpointHeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EndpointHeartbeatResponse) GetShellRequests() []*ShellRequest {
	if x != nil {
		return x.ShellRequests
	}
	return nil
}

func (x *EndpointHeartbeatResponse) GetK8SapiProxyRequests() []*K8SAPIProxyRequest {
	if x != nil {
		return x.K8SapiProxyRequests
	}
	return nil
}

func (x *EndpointHeartbeatResponse) GetSvcProxyRequests() []*SVCProxyRequest {
	if x != nil {
		return x.SvcProxyRequests
	}
	return nil
}

func (x *EndpointHeartbeatResponse) GetSshEnabled() bool {
	if x != nil {
		return x.SshEnabled
	}
	return false
}

func (x *EndpointHeartbeatResponse) GetSshEnabledSet() bool {
	if x != nil {
		return x.SshEnabledSet
	}
	return false
}

func (x *EndpointHeartbeatResponse) GetK8SapiEnabled() bool {
	if x != nil {
		return x.K8SapiEnabled
	}
	return false
}

func (x *EndpointHeartbeatResponse) GetK8SapiEnabledSet() bool {
	if x != nil {
		return x.K8SapiEnabledSet
	}
	return false
}

func (x *EndpointHeartbeatResponse) GetK8SapiApiServer() string {
	if x != nil {
		return x.K8SapiApiServer
	}
	return ""
}

func (x *EndpointHeartbeatResponse) GetK8SserviceEnabled() bool {
	if x != nil {
		return x.K8SserviceEnabled
	}
	return false
}

func (x *EndpointHeartbeatResponse) GetK8SserviceEnabledSet() bool {
	if x != nil {
		return x.K8SserviceEnabledSet
	}
	return false
}

// DiscoveredK8SService 发现的 K8S Service（Endpoint/Agent 心跳上报）
type DiscoveredK8SService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`                                                                     // 命名空间
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`                                              // Service 名称
	ClusterIp     string                 `protobuf:"bytes,3,opt,name=cluster_ip,json=clusterIp,proto3" json:"cluster_ip,omitempty"`                                                    // ClusterIP
	Ports         []*ServicePort         `protobuf:"bytes,4,rep,name=ports,proto3" json:"ports,omitempty"`                                                                             // 端口列表
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 标签
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveredK8SService) Reset() {
	*x = DiscoveredK8SService{}
	mi := &file_pkg_proto_endpoint_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveredK8SService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveredK8SService) ProtoMessage() {}

func (x *DiscoveredK8SService) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_endpoint_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveredK8SService.ProtoReflect.Descriptor instead.
func (*DiscoveredK8SService) Descriptor() ([]byte, []int) {
	return file_pkg_proto_endpoint_proto_rawDescGZIP(), []int{5}
}

func (x *DiscoveredK8SService) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DiscoveredK8SService) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *DiscoveredK8SService) GetClusterIp() string {
	if x != nil {
		return x.ClusterIp
	}
	return ""
}

func (x *DiscoveredK8SService) GetPorts() []*ServicePort {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *DiscoveredK8SService) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// ServicePort K8S Service 端口
type ServicePort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`         // 端口名称
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`        // 端口号
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"` // 协议（TCP/UDP）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServicePort) Reset() {
	*x = ServicePort{}
	mi := &file_pkg_proto_endpoint_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServicePort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicePort) ProtoMessage() {}

func (x *ServicePort) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_endpoint_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicePort.ProtoReflect.Descriptor instead.
func (*ServicePort) Descriptor() ([]byte, []int) {
	return file_pkg_proto_endpoint_proto_rawDescGZIP(), []int{6}
}

func (x *ServicePort) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServicePort) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServicePort) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

// ShellRequest Agent 通知 Endpoint 的 Shell 请求
type ShellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话 ID（Agent 生成，Endpoint 回调时携带）
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`                          // 登录用户名（如 "root"）
	Rows          uint32                 `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`                           // 终端行数
	Cols          uint32                 `protobuf:"varint,4,opt,name=cols,proto3" json:"cols,omitempty"`                           // 终端列数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellRequest) Reset() {
	*x = ShellRequest{}
	mi := &file_pkg_proto_endpoint_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellRequest) ProtoMessage() {}

func (x *ShellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_endpoint_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellRequest.ProtoReflect.Descriptor instead.
func (*ShellRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_endpoint_proto_rawDescGZIP(), []int{7}
}

func (x *ShellRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ShellRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *ShellRequest) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *ShellRequest) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

// ShellData Endpoint Shell 会话数据帧
type ShellData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOpen        bool                   `protobuf:"varint,1,opt,name=is_open,json=isOpen,proto3" json:"is_open,omitempty"`         // 是否为开启会话请求（首包 true）
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话 ID
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`                          // 注册令牌（首包携带）
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`                            // 数据载荷（stdin / stdout）
	IsResize      bool                   `protobuf:"varint,5,opt,name=is_resize,json=isResize,proto3" json:"is_resize,omitempty"`   // 是否为窗口大小变更
	Rows          uint32                 `protobuf:"varint,6,opt,name=rows,proto3" json:"rows,omitempty"`                           // 新的终端行数
	Cols          uint32                 `protobuf:"varint,7,opt,name=cols,proto3" json:"cols,omitempty"`                           // 新的终端列数
	IsClose       bool                   `protobuf:"varint,8,opt,name=is_close,json=isClose,proto3" json:"is_close,omitempty"`      // 是否为关闭通知
	ExitCode      int32                  `protobuf:"varint,9,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`   // 退出码
	Error         string                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`                         // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellData) Reset() {
	*x = ShellData{}
	mi := &file_pkg_proto_endpoint_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellData) ProtoMessage() {}

func (x *ShellData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_endpoint_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellData.ProtoReflect.Descriptor instead.
func (*ShellData) Descriptor() ([]byte, []int) {
	return file_pkg_proto_endpoint_proto_rawDescGZIP(), []int{8}
}

func (x *ShellData) GetIsOpen() bool {
	if x != nil {
		return x.IsOpen
	}
	return false
}

func (x *ShellData) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ShellData) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ShellData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ShellData) GetIsResize() bool {
	if x != nil {
		return x.IsResize
	}
	return false
}

func (x *ShellData) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *ShellData) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *ShellData) GetIsClose() bool {
	if x != nil {
		return x.IsClose
	}
	return false
}

func (x *ShellData) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ShellData) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// K8SAPIProxyRequest Agent 通知 Endpoint 的 K8S API 代理请求
type K8SAPIProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *K8SAPIProxyRequest) Reset() {
	*x = K8SAPIProxyRequest{}
	mi := &file_pkg_proto_endpoint_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SAPIProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SAPIProxyRequest) ProtoMessage() {}

func (x *K8SAPIProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_endpoint_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SAPIProxyRequest.ProtoReflect.Descriptor instead.
func (*K8SAPIProxyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_endpoint_proto_rawDescGZIP(), []int{9}
}

func (x *K8SAPIProxyRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// K8SAPIProxyData Endpoint K8S API 代理数据帧
type K8SAPIProxyData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOpen        bool                   `protobuf:"varint,1,opt,name=is_open,json=isOpen,proto3" json:"is_open,omitempty"`         // 是否为开启会话请求（首包 true）
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话 ID
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`                          // 注册令牌（首包携带）
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`                            // 数据载荷
	IsClose       bool                   `protobuf:"varint,5,opt,name=is_close,json=isClose,proto3" json:"is_close,omitempty"`      // 是否为关闭通知
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`                          // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *K8SAPIProxyData) Reset() {
	*x = K8SAPIProxyData{}
	mi := &file_pkg_proto_endpoint_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SAPIProxyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SAPIProxyData) ProtoMessage() {}

func (x *K8SAPIProxyData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_endpoint_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SAPIProxyData.ProtoReflect.Descriptor instead.
func (*K8SAPIProxyData) Descriptor() ([]byte, []int) {
	return file_pkg_proto_endpoint_proto_rawDescGZIP(), []int{10}
}

func (x *K8SAPIProxyData) GetIsOpen() bool {
	if x != nil {
		return x.IsOpen
	}
	return false
}

func (x *K8SAPIProxyData) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *K8SAPIProxyData) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *K8SAPIProxyData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *K8SAPIProxyData) GetIsClose() bool {
	if x != nil {
		return x.IsClose
	}
	return false
}

func (x *K8SAPIProxyData) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// SVCProxyRequest Agent 通知 Endpoint 的 K8S Service 代理请求
type SVCProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`       // 会话 ID
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`                        // 目标命名空间
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // 目标 Service 名称
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`                                 // 目标端口
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SVCProxyRequest) Reset() {
	*x = SVCProxyRequest{}
	mi := &file_pkg_proto_endpoint_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SVCProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SVCProxyRequest) ProtoMessage() {}

func (x *SVCProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_endpoint_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SVCProxyRequest.ProtoReflect.Descriptor instead.
func (*SVCProxyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_endpoint_proto_rawDescGZIP(), []int{11}
}

func (x *SVCProxyRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SVCProxyRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SVCProxyRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *SVCProxyRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// EndpointSVCProxyData Endpoint K8S Service 代理数据帧
type EndpointSVCProxyData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOpen        bool                   `protobuf:"varint,1,opt,name=is_open,json=isOpen,proto3" json:"is_open,omitempty"`         // 是否为开启会话请求（首包 true）
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话 ID
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`                          // 注册令牌（首包携带）
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`                            // 数据载荷
	IsClose       bool                   `protobuf:"varint,5,opt,name=is_close,json=isClose,proto3" json:"is_close,omitempty"`      // 是否为关闭通知
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`                          // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointSVCProxyData) Reset() {
	*x = EndpointSVCProxyData{}
	mi := &file_pkg_proto_endpoint_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointSVCProxyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointSVCProxyData) ProtoMessage() {}

func (x *EndpointSVCProxyData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_endpoint_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointSVCProxyData.ProtoReflect.Descriptor instead.
func (*EndpointSVCProxyData) Descriptor() ([]byte, []int) {
	return file_pkg_proto_endpoint_proto_rawDescGZIP(), []int{12}
}

func (x *EndpointSVCProxyData) GetIsOpen() bool {
	if x != nil {
		return x.IsOpen
	}
	return false
}

func (x *EndpointSVCProxyData) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EndpointSVCProxyData) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EndpointSVCProxyData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EndpointSVCProxyData) GetIsClose() bool {
	if x != nil {
		return x.IsClose
	}
	return false
}

func (x *EndpointSVCProxyData) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_proto_endpoint_proto protoreflect.FileDescriptor

const file_pkg_proto_endpoint_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/proto/endpoint.proto\x12\x12awecloud.signaling\"]\n" +
	"\x17EndpointRegisterRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"o\n" +
	"\x18EndpointRegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vendpoint_id\x18\x03 \x01(\tR\n" +
	"endpointId\"\xa9\x03\n" +
	"\x18EndpointHeartbeatRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12N\n" +
	"\fcapabilities\x18\x03 \x03(\v2*.awecloud.signaling.EndpointCapabilityInfoR\fcapabilities\x12Y\n" +
	"\x13discovered_services\x18\x04 \x03(\v2(.awecloud.signaling.DiscoveredK8SServiceR\x12discoveredServices\x12\x1b\n" +
	"\tssh_users\x18\a \x03(\tR\bsshUsers\x12*\n" +
	"\x11k8sapi_api_server\x18\b \x01(\tR\x0fk8sapiApiServer\x12:\n" +
	"\x19k8sservice_label_selector\x18\t \x01(\tR\x17k8sserviceLabelSelector\x123\n" +
	"\x15k8sservice_namespaces\x18\n" +
	" \x03(\tR\x14k8sserviceNamespaces\"s\n" +
	"\x16EndpointCapabilityInfo\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1d\n" +
	"\n" +
	"api_server\x18\x04 \x01(\tR\tapiServer\"\xf6\x04\n" +
	"\x19EndpointHeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12G\n" +
	"\x0eshell_requests\x18\x03 \x03(\v2 .awecloud.signaling.ShellRequestR\rshellRequests\x12Z\n" +
	"\x15k8sapi_proxy_requests\x18\x04 \x03(\v2&.awecloud.signaling.K8SAPIProxyRequestR\x13k8sapiProxyRequests\x12Q\n" +
	"\x12svc_proxy_requests\x18\x05 \x03(\v2#.awecloud.signaling.SVCProxyRequestR\x10svcProxyRequests\x12\x1f\n" +
	"\vssh_enabled\x18\n" +
	" \x01(\bR\n" +
	"sshEnabled\x12&\n" +
	"\x0fssh_enabled_set\x18\v \x01(\bR\rsshEnabledSet\x12%\n" +
	"\x0ek8sapi_enabled\x18\f \x01(\bR\rk8sapiEnabled\x12,\n" +
	"\x12k8sapi_enabled_set\x18\r \x01(\bR\x10k8sapiEnabledSet\x12*\n" +
	"\x11k8sapi_api_server\x18\x0e \x01(\tR\x0fk8sapiApiServer\x12-\n" +
	"\x12k8sservice_enabled\x18\x0f \x01(\bR\x11k8sserviceEnabled\x124\n" +
	"\x16k8sservice_enabled_set\x18\x10 \x01(\bR\x14k8sserviceEnabledSet\"\xb6\x02\n" +
	"\x14DiscoveredK8SService\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x1d\n" +
	"\n" +
	"cluster_ip\x18\x03 \x01(\tR\tclusterIp\x125\n" +
	"\x05ports\x18\x04 \x03(\v2\x1f.awecloud.signaling.ServicePortR\x05ports\x12L\n" +
	"\x06labels\x18\x05 \x03(\v24.awecloud.signaling.DiscoveredK8SService.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Q\n" +
	"\vServicePort\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"k\n" +
	"\fShellRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x04 \x01(\rR\x04cols\"\x80\x02\n" +
	"\tShellData\x12\x17\n" +
	"\ais_open\x18\x01 \x01(\bR\x06isOpen\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1b\n" +
	"\tis_resize\x18\x05 \x01(\bR\bisResize\x12\x12\n" +
	"\x04rows\x18\x06 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\a \x01(\rR\x04cols\x12\x19\n" +
	"\bis_close\x18\b \x01(\bR\aisClose\x12\x1b\n" +
	"\texit_code\x18\t \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\"3\n" +
	"\x12K8SAPIProxyRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xa4\x01\n" +
	"\x0fK8SAPIProxyData\x12\x17\n" +
	"\ais_open\x18\x01 \x01(\bR\x06isOpen\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x19\n" +
	"\bis_close\x18\x05 \x01(\bR\aisClose\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\x85\x01\n" +
	"\x0fSVCProxyRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\"\xa9\x01\n" +
	"\x14EndpointSVCProxyData\x12\x17\n" +
	"\ais_open\x18\x01 \x01(\bR\x06isOpen\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x19\n" +
	"\bis_close\x18\x05 \x01(\bR\aisClose\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error2\xfe\x03\n" +
	"\x0fEndpointService\x12e\n" +
	"\bRegister\x12+.awecloud.signaling.EndpointRegisterRequest\x1a,.awecloud.signaling.EndpointRegisterResponse\x12l\n" +
	"\tHeartbeat\x12,.awecloud.signaling.EndpointHeartbeatRequest\x1a-.awecloud.signaling.EndpointHeartbeatResponse(\x010\x01\x12M\n" +
	"\tOpenShell\x12\x1d.awecloud.signaling.ShellData\x1a\x1d.awecloud.signaling.ShellData(\x010\x01\x12_\n" +
	"\x0fOpenK8SAPIProxy\x12#.awecloud.signaling.K8SAPIProxyData\x1a#.awecloud.signaling.K8SAPIProxyData(\x010\x01\x12f\n" +
	"\fOpenSVCProxy\x12(.awecloud.signaling.EndpointSVCProxyData\x1a(.awecloud.signaling.EndpointSVCProxyData(\x010\x01B<Z:github.com/open-beagle/awecloud-signaling-server/pkg/protob\x06proto3"

var (
	file_pkg_proto_endpoint_proto_rawDescOnce sync.Once
	file_pkg_proto_endpoint_proto_rawDescData []byte
)

func file_pkg_proto_endpoint_proto_rawDescGZIP() []byte {
	file_pkg_proto_endpoint_proto_rawDescOnce.Do(func() {
		file_pkg_proto_endpoint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_endpoint_proto_rawDesc), len(file_pkg_proto_endpoint_proto_rawDesc)))
	})
	return file_pkg_proto_endpoint_proto_rawDescData
}

var file_pkg_proto_endpoint_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pkg_proto_endpoint_proto_goTypes = []any{
	(*EndpointRegisterRequest)(nil),   // 0: awecloud.signaling.EndpointRegisterRequest
	(*EndpointRegisterResponse)(nil),  // 1: awecloud.signaling.EndpointRegisterResponse
	(*EndpointHeartbeatRequest)(nil),  // 2: awecloud.signaling.EndpointHeartbeatRequest
	(*EndpointCapabilityInfo)(nil),    // 3: awecloud.signaling.EndpointCapabilityInfo
	(*EndpointHeartbeatResponse)(nil), // 4: awecloud.signaling.EndpointHeartbeatResponse
	(*DiscoveredK8SService)(nil),      // 5: awecloud.signaling.DiscoveredK8SService
	(*ServicePort)(nil),               // 6: awecloud.signaling.ServicePort
	(*ShellRequest)(nil),              // 7: awecloud.signaling.ShellRequest
	(*ShellData)(nil),                 // 8: awecloud.signaling.ShellData
	(*K8SAPIProxyRequest)(nil),        // 9: awecloud.signaling.K8SAPIProxyRequest
	(*K8SAPIProxyData)(nil),           // 10: awecloud.signaling.K8SAPIProxyData
	(*SVCProxyRequest)(nil),           // 11: awecloud.signaling.SVCProxyRequest
	(*EndpointSVCProxyData)(nil),      // 12: awecloud.signaling.EndpointSVCProxyData
	nil,                               // 13: awecloud.signaling.DiscoveredK8SService.LabelsEntry
}
var file_pkg_proto_endpoint_proto_depIdxs = []int32{
	3,  // 0: awecloud.signaling.EndpointHeartbeatRequest.capabilities:type_name -> awecloud.signaling.EndpointCapabilityInfo
	5,  // 1: awecloud.signaling.EndpointHeartbeatRequest.discovered_services:type_name -> awecloud.signaling.DiscoveredK8SService
	7,  // 2: awecloud.signaling.EndpointHeartbeatResponse.shell_requests:type_name -> awecloud.signaling.ShellRequest
	9,  // 3: awecloud.signaling.EndpointHeartbeatResponse.k8sapi_proxy_requests:type_name -> awecloud.signaling.K8SAPIProxyRequest
	11, // 4: awecloud.signaling.EndpointHeartbeatResponse.svc_proxy_requests:type_name -> awecloud.signaling.SVCProxyRequest
	6,  // 5: awecloud.signaling.DiscoveredK8SService.ports:type_name -> awecloud.signaling.ServicePort
	13, // 6: awecloud.signaling.DiscoveredK8SService.labels:type_name -> awecloud.signaling.DiscoveredK8SService.LabelsEntry
	0,  // 7: awecloud.signaling.EndpointService.Register:input_type -> awecloud.signaling.EndpointRegisterRequest
	2,  // 8: awecloud.signaling.EndpointService.Heartbeat:input_type -> awecloud.signaling.EndpointHeartbeatRequest
	8,  // 9: awecloud.signaling.EndpointService.OpenShell:input_type -> awecloud.signaling.ShellData
	10, // 10: awecloud.signaling.EndpointService.OpenK8SAPIProxy:input_type -> awecloud.signaling.K8SAPIProxyData
	12, // 11: awecloud.signaling.EndpointService.OpenSVCProxy:input_type -> awecloud.signaling.EndpointSVCProxyData
	1,  // 12: awecloud.signaling.EndpointService.Register:output_type -> awecloud.signaling.EndpointRegisterResponse
	4,  // 13: awecloud.signaling.EndpointService.Heartbeat:output_type -> awecloud.signaling.EndpointHeartbeatResponse
	8,  // 14: awecloud.signaling.EndpointService.OpenShell:output_type -> awecloud.signaling.ShellData
	10, // 15: awecloud.signaling.EndpointService.OpenK8SAPIProxy:output_type -> awecloud.signaling.K8SAPIProxyData
	12, // 16: awecloud.signaling.EndpointService.OpenSVCProxy:output_type -> awecloud.signaling.EndpointSVCProxyData
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pkg_proto_endpoint_proto_init() }
func file_pkg_proto_endpoint_proto_init() {
	if File_pkg_proto_endpoint_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_endpoint_proto_rawDesc), len(file_pkg_proto_endpoint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_endpoint_proto_goTypes,
		DependencyIndexes: file_pkg_proto_endpoint_proto_depIdxs,
		MessageInfos:      file_pkg_proto_endpoint_proto_msgTypes,
	}.Build()
	File_pkg_proto_endpoint_proto = out.File
	file_pkg_proto_endpoint_proto_goTypes = nil
	file_pkg_proto_endpoint_proto_depIdxs = nil
}
