// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.3
// source: pkg/proto/endpoint.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EndpointService_Register_FullMethodName        = "/awecloud.signaling.EndpointService/Register"
	EndpointService_Heartbeat_FullMethodName       = "/awecloud.signaling.EndpointService/Heartbeat"
	EndpointService_OpenShell_FullMethodName       = "/awecloud.signaling.EndpointService/OpenShell"
	EndpointService_OpenK8SAPIProxy_FullMethodName = "/awecloud.signaling.EndpointService/OpenK8SAPIProxy"
	EndpointService_OpenSVCProxy_FullMethodName    = "/awecloud.signaling.EndpointService/OpenSVCProxy"
	EndpointService_OpenRawStream_FullMethodName   = "/awecloud.signaling.EndpointService/OpenRawStream"
)

// EndpointServiceClient is the client API for EndpointService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EndpointService Endpoint 管理服务（Agent 端实现，监听内网 50052 端口）
type EndpointServiceClient interface {
	// 注册 - Endpoint 连接 Agent 时调用，用 token 认证并注册自己
	Register(ctx context.Context, in *EndpointRegisterRequest, opts ...grpc.CallOption) (*EndpointRegisterResponse, error)
	// 心跳 - Endpoint 定期上报状态，Agent 下发配置
	Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EndpointHeartbeatRequest, EndpointHeartbeatResponse], error)
	// OpenShell - Agent 指令 Endpoint 开启 shell 会话（gRPC 双向流）
	OpenShell(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ShellData, ShellData], error)
	// OpenK8SAPIProxy - Agent 指令 Endpoint 开启 K8S API 代理（gRPC 双向流）
	OpenK8SAPIProxy(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[K8SAPIProxyData, K8SAPIProxyData], error)
	// OpenSVCProxy - Agent 指令 Endpoint 开启 K8S Service 代理（gRPC 双向流）
	OpenSVCProxy(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EndpointSVCProxyData, EndpointSVCProxyData], error)
	// OpenRawStream - Agent 指令 Endpoint 开启原始字节流（用于协议升级，如 kubectl logs/exec）
	OpenRawStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RawStreamData, RawStreamData], error)
}

type endpointServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEndpointServiceClient(cc grpc.ClientConnInterface) EndpointServiceClient {
	return &endpointServiceClient{cc}
}

func (c *endpointServiceClient) Register(ctx context.Context, in *EndpointRegisterRequest, opts ...grpc.CallOption) (*EndpointRegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EndpointRegisterResponse)
	err := c.cc.Invoke(ctx, EndpointService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointServiceClient) Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EndpointHeartbeatRequest, EndpointHeartbeatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EndpointService_ServiceDesc.Streams[0], EndpointService_Heartbeat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EndpointHeartbeatRequest, EndpointHeartbeatResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EndpointService_HeartbeatClient = grpc.BidiStreamingClient[EndpointHeartbeatRequest, EndpointHeartbeatResponse]

func (c *endpointServiceClient) OpenShell(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ShellData, ShellData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EndpointService_ServiceDesc.Streams[1], EndpointService_OpenShell_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ShellData, ShellData]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EndpointService_OpenShellClient = grpc.BidiStreamingClient[ShellData, ShellData]

func (c *endpointServiceClient) OpenK8SAPIProxy(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[K8SAPIProxyData, K8SAPIProxyData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EndpointService_ServiceDesc.Streams[2], EndpointService_OpenK8SAPIProxy_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[K8SAPIProxyData, K8SAPIProxyData]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EndpointService_OpenK8SAPIProxyClient = grpc.BidiStreamingClient[K8SAPIProxyData, K8SAPIProxyData]

func (c *endpointServiceClient) OpenSVCProxy(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EndpointSVCProxyData, EndpointSVCProxyData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EndpointService_ServiceDesc.Streams[3], EndpointService_OpenSVCProxy_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EndpointSVCProxyData, EndpointSVCProxyData]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EndpointService_OpenSVCProxyClient = grpc.BidiStreamingClient[EndpointSVCProxyData, EndpointSVCProxyData]

func (c *endpointServiceClient) OpenRawStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RawStreamData, RawStreamData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EndpointService_ServiceDesc.Streams[4], EndpointService_OpenRawStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RawStreamData, RawStreamData]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EndpointService_OpenRawStreamClient = grpc.BidiStreamingClient[RawStreamData, RawStreamData]

// EndpointServiceServer is the server API for EndpointService service.
// All implementations must embed UnimplementedEndpointServiceServer
// for forward compatibility.
//
// EndpointService Endpoint 管理服务（Agent 端实现，监听内网 50052 端口）
type EndpointServiceServer interface {
	// 注册 - Endpoint 连接 Agent 时调用，用 token 认证并注册自己
	Register(context.Context, *EndpointRegisterRequest) (*EndpointRegisterResponse, error)
	// 心跳 - Endpoint 定期上报状态，Agent 下发配置
	Heartbeat(grpc.BidiStreamingServer[EndpointHeartbeatRequest, EndpointHeartbeatResponse]) error
	// OpenShell - Agent 指令 Endpoint 开启 shell 会话（gRPC 双向流）
	OpenShell(grpc.BidiStreamingServer[ShellData, ShellData]) error
	// OpenK8SAPIProxy - Agent 指令 Endpoint 开启 K8S API 代理（gRPC 双向流）
	OpenK8SAPIProxy(grpc.BidiStreamingServer[K8SAPIProxyData, K8SAPIProxyData]) error
	// OpenSVCProxy - Agent 指令 Endpoint 开启 K8S Service 代理（gRPC 双向流）
	OpenSVCProxy(grpc.BidiStreamingServer[EndpointSVCProxyData, EndpointSVCProxyData]) error
	// OpenRawStream - Agent 指令 Endpoint 开启原始字节流（用于协议升级，如 kubectl logs/exec）
	OpenRawStream(grpc.BidiStreamingServer[RawStreamData, RawStreamData]) error
	mustEmbedUnimplementedEndpointServiceServer()
}

// UnimplementedEndpointServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEndpointServiceServer struct{}

func (UnimplementedEndpointServiceServer) Register(context.Context, *EndpointRegisterRequest) (*EndpointRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedEndpointServiceServer) Heartbeat(grpc.BidiStreamingServer[EndpointHeartbeatRequest, EndpointHeartbeatResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedEndpointServiceServer) OpenShell(grpc.BidiStreamingServer[ShellData, ShellData]) error {
	return status.Errorf(codes.Unimplemented, "method OpenShell not implemented")
}
func (UnimplementedEndpointServiceServer) OpenK8SAPIProxy(grpc.BidiStreamingServer[K8SAPIProxyData, K8SAPIProxyData]) error {
	return status.Errorf(codes.Unimplemented, "method OpenK8SAPIProxy not implemented")
}
func (UnimplementedEndpointServiceServer) OpenSVCProxy(grpc.BidiStreamingServer[EndpointSVCProxyData, EndpointSVCProxyData]) error {
	return status.Errorf(codes.Unimplemented, "method OpenSVCProxy not implemented")
}
func (UnimplementedEndpointServiceServer) OpenRawStream(grpc.BidiStreamingServer[RawStreamData, RawStreamData]) error {
	return status.Errorf(codes.Unimplemented, "method OpenRawStream not implemented")
}
func (UnimplementedEndpointServiceServer) mustEmbedUnimplementedEndpointServiceServer() {}
func (UnimplementedEndpointServiceServer) testEmbeddedByValue()                         {}

// UnsafeEndpointServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EndpointServiceServer will
// result in compilation errors.
type UnsafeEndpointServiceServer interface {
	mustEmbedUnimplementedEndpointServiceServer()
}

func RegisterEndpointServiceServer(s grpc.ServiceRegistrar, srv EndpointServiceServer) {
	// If the following call pancis, it indicates UnimplementedEndpointServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EndpointService_ServiceDesc, srv)
}

func _EndpointService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndpointRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndpointService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointServiceServer).Register(ctx, req.(*EndpointRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndpointService_Heartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EndpointServiceServer).Heartbeat(&grpc.GenericServerStream[EndpointHeartbeatRequest, EndpointHeartbeatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EndpointService_HeartbeatServer = grpc.BidiStreamingServer[EndpointHeartbeatRequest, EndpointHeartbeatResponse]

func _EndpointService_OpenShell_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EndpointServiceServer).OpenShell(&grpc.GenericServerStream[ShellData, ShellData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EndpointService_OpenShellServer = grpc.BidiStreamingServer[ShellData, ShellData]

func _EndpointService_OpenK8SAPIProxy_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EndpointServiceServer).OpenK8SAPIProxy(&grpc.GenericServerStream[K8SAPIProxyData, K8SAPIProxyData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EndpointService_OpenK8SAPIProxyServer = grpc.BidiStreamingServer[K8SAPIProxyData, K8SAPIProxyData]

func _EndpointService_OpenSVCProxy_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EndpointServiceServer).OpenSVCProxy(&grpc.GenericServerStream[EndpointSVCProxyData, EndpointSVCProxyData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EndpointService_OpenSVCProxyServer = grpc.BidiStreamingServer[EndpointSVCProxyData, EndpointSVCProxyData]

func _EndpointService_OpenRawStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EndpointServiceServer).OpenRawStream(&grpc.GenericServerStream[RawStreamData, RawStreamData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EndpointService_OpenRawStreamServer = grpc.BidiStreamingServer[RawStreamData, RawStreamData]

// EndpointService_ServiceDesc is the grpc.ServiceDesc for EndpointService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EndpointService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "awecloud.signaling.EndpointService",
	HandlerType: (*EndpointServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _EndpointService_Register_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Heartbeat",
			Handler:       _EndpointService_Heartbeat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "OpenShell",
			Handler:       _EndpointService_OpenShell_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "OpenK8SAPIProxy",
			Handler:       _EndpointService_OpenK8SAPIProxy_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "OpenSVCProxy",
			Handler:       _EndpointService_OpenSVCProxy_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "OpenRawStream",
			Handler:       _EndpointService_OpenRawStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/proto/endpoint.proto",
}
