// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: pkg/proto/update.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateDirective struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Component     string                 `protobuf:"bytes,2,opt,name=component,proto3" json:"component,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	ArtifactId    string                 `protobuf:"bytes,4,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,5,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	Filename      string                 `protobuf:"bytes,6,opt,name=filename,proto3" json:"filename,omitempty"`
	Os            string                 `protobuf:"bytes,7,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,8,opt,name=arch,proto3" json:"arch,omitempty"`
	Size          int64                  `protobuf:"varint,9,opt,name=size,proto3" json:"size,omitempty"`
	Sha256        string                 `protobuf:"bytes,10,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Force         bool                   `protobuf:"varint,13,opt,name=force,proto3" json:"force,omitempty"`
	NotBeforeUnix int64                  `protobuf:"varint,14,opt,name=not_before_unix,json=notBeforeUnix,proto3" json:"not_before_unix,omitempty"`
	DeadlineUnix  int64                  `protobuf:"varint,15,opt,name=deadline_unix,json=deadlineUnix,proto3" json:"deadline_unix,omitempty"`
	Action        string                 `protobuf:"bytes,16,opt,name=action,proto3" json:"action,omitempty"`
	TargetName    string                 `protobuf:"bytes,17,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
	CommitId      string                 `protobuf:"bytes,18,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDirective) Reset() {
	*x = UpdateDirective{}
	mi := &file_pkg_proto_update_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDirective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDirective) ProtoMessage() {}

func (x *UpdateDirective) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_update_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDirective.ProtoReflect.Descriptor instead.
func (*UpdateDirective) Descriptor() ([]byte, []int) {
	return file_pkg_proto_update_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateDirective) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *UpdateDirective) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *UpdateDirective) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UpdateDirective) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *UpdateDirective) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *UpdateDirective) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UpdateDirective) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *UpdateDirective) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *UpdateDirective) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UpdateDirective) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *UpdateDirective) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *UpdateDirective) GetNotBeforeUnix() int64 {
	if x != nil {
		return x.NotBeforeUnix
	}
	return 0
}

func (x *UpdateDirective) GetDeadlineUnix() int64 {
	if x != nil {
		return x.DeadlineUnix
	}
	return 0
}

func (x *UpdateDirective) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *UpdateDirective) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

func (x *UpdateDirective) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

type UpdateStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Phase           string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	Progress        int32                  `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"`
	CurrentVersion  string                 `protobuf:"bytes,4,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	Sequence        int64                  `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ErrorCode       string                 `protobuf:"bytes,6,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CurrentCommitId string                 `protobuf:"bytes,8,opt,name=current_commit_id,json=currentCommitId,proto3" json:"current_commit_id,omitempty"`
	CurrentSha256   string                 `protobuf:"bytes,9,opt,name=current_sha256,json=currentSha256,proto3" json:"current_sha256,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateStatus) Reset() {
	*x = UpdateStatus{}
	mi := &file_pkg_proto_update_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatus) ProtoMessage() {}

func (x *UpdateStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_update_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatus.ProtoReflect.Descriptor instead.
func (*UpdateStatus) Descriptor() ([]byte, []int) {
	return file_pkg_proto_update_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateStatus) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *UpdateStatus) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *UpdateStatus) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *UpdateStatus) GetCurrentVersion() string {
	if x != nil {
		return x.CurrentVersion
	}
	return ""
}

func (x *UpdateStatus) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *UpdateStatus) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *UpdateStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *UpdateStatus) GetCurrentCommitId() string {
	if x != nil {
		return x.CurrentCommitId
	}
	return ""
}

func (x *UpdateStatus) GetCurrentSha256() string {
	if x != nil {
		return x.CurrentSha256
	}
	return ""
}

var File_pkg_proto_update_proto protoreflect.FileDescriptor

const file_pkg_proto_update_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/proto/update.proto\x12\x12awecloud.signaling\"\xd7\x03\n" +
	"\x0fUpdateDirective\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1c\n" +
	"\tcomponent\x18\x02 \x01(\tR\tcomponent\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1f\n" +
	"\vartifact_id\x18\x04 \x01(\tR\n" +
	"artifactId\x12!\n" +
	"\fdownload_url\x18\x05 \x01(\tR\vdownloadUrl\x12\x1a\n" +
	"\bfilename\x18\x06 \x01(\tR\bfilename\x12\x0e\n" +
	"\x02os\x18\a \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\b \x01(\tR\x04arch\x12\x12\n" +
	"\x04size\x18\t \x01(\x03R\x04size\x12\x16\n" +
	"\x06sha256\x18\n" +
	" \x01(\tR\x06sha256\x12\x14\n" +
	"\x05force\x18\r \x01(\bR\x05force\x12&\n" +
	"\x0fnot_before_unix\x18\x0e \x01(\x03R\rnotBeforeUnix\x12#\n" +
	"\rdeadline_unix\x18\x0f \x01(\x03R\fdeadlineUnix\x12\x16\n" +
	"\x06action\x18\x10 \x01(\tR\x06action\x12\x1f\n" +
	"\vtarget_name\x18\x11 \x01(\tR\n" +
	"targetName\x12\x1b\n" +
	"\tcommit_id\x18\x12 \x01(\tR\bcommitIdJ\x04\b\v\x10\fJ\x04\b\f\x10\r\"\xb5\x02\n" +
	"\fUpdateStatus\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x05R\bprogress\x12'\n" +
	"\x0fcurrent_version\x18\x04 \x01(\tR\x0ecurrentVersion\x12\x1a\n" +
	"\bsequence\x18\x05 \x01(\x03R\bsequence\x12\x1d\n" +
	"\n" +
	"error_code\x18\x06 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\x12*\n" +
	"\x11current_commit_id\x18\b \x01(\tR\x0fcurrentCommitId\x12%\n" +
	"\x0ecurrent_sha256\x18\t \x01(\tR\rcurrentSha256B<Z:github.com/open-beagle/awecloud-signaling-server/pkg/protob\x06proto3"

var (
	file_pkg_proto_update_proto_rawDescOnce sync.Once
	file_pkg_proto_update_proto_rawDescData []byte
)

func file_pkg_proto_update_proto_rawDescGZIP() []byte {
	file_pkg_proto_update_proto_rawDescOnce.Do(func() {
		file_pkg_proto_update_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_update_proto_rawDesc), len(file_pkg_proto_update_proto_rawDesc)))
	})
	return file_pkg_proto_update_proto_rawDescData
}

var file_pkg_proto_update_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_update_proto_goTypes = []any{
	(*UpdateDirective)(nil), // 0: awecloud.signaling.UpdateDirective
	(*UpdateStatus)(nil),    // 1: awecloud.signaling.UpdateStatus
}
var file_pkg_proto_update_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_update_proto_init() }
func file_pkg_proto_update_proto_init() {
	if File_pkg_proto_update_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_update_proto_rawDesc), len(file_pkg_proto_update_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_update_proto_goTypes,
		DependencyIndexes: file_pkg_proto_update_proto_depIdxs,
		MessageInfos:      file_pkg_proto_update_proto_msgTypes,
	}.Build()
	File_pkg_proto_update_proto = out.File
	file_pkg_proto_update_proto_goTypes = nil
	file_pkg_proto_update_proto_depIdxs = nil
}
